hirosystems/clarinet

deno/index.ts
fixed a typo `Tx.trasnferStx -> Tx.transferStx`
=> fix: Tx.transferStx typo

README.md
This fixes #7 by adding a note about installing Rust and the required packages for Debian/Ubuntu Linux.
=> add prereqs to readme for build from source

.github/workflows/ci.yaml
* Updates artifact names
* Don't run CI after semantic-release pushes up Cargo files.
* Fixes Windows functional tests
Closes https://github.com/hirosystems/clarinet/issues/60
=> ci: update workflow

.github/workflows/open-develop-pr.yml
On release, the semantic-release plugin will create a commit to update the CHANGELOG and some other files, and then tag that commit with the new version. If someone then pushes a commit to the `develop` branch, semantic-release will create a new release candidate using the _previous_ version tag.
This is because when analyzing the commits in the `develop` branch, it does not see the recently-generated tag available on the `develop` branch. Ideally, a PR would be opened against the develop branch automatically after a release is performed to port over the new commit and tag from the `main` branch.
This would allow any further new commits to the `develop` branch to generate a release candidate with the most up-to-date tag version from `main`.
=> ci: add new workflow to update develop branch on release

src/frontend/cli.rs, src/test/deno.rs
This PR is batching 2 issues:
- https://github.com/hirosystems/clarinet/issues/70: it looks like using `deno` concurrently with `clarinet`, either directly or via the deno vs-code extension, could cause some issues where a cache of the project is created, that clarinet then tries to use by default. This fix is making sure that `clarinet test` does not try to use this aforementioned cache.
- The `clarinet deploy` command always try to use localhost, instead of using the path coming from the network manifest.
=> Fix: batch of one liners

.github/workflows/ci.yaml, .github/workflows/open-develop-pr.yml, .github/workflows/pkg-version-bump.yaml
Changes the release process to:
- wait until all packages have been built and uploaded to the GH release before attempting to rev the package manager manifests
- use a different GH action to open a PR, as the previous action being used would overwrite the latest commit in the `main` branch
=> ci: update release workflows

.github/workflows/ci.yaml, node-bindings/package-lock.json, node-bindings/package.json, node-bindings/src/lib.rs, package.json, src/integrate/mod.rs
Closes https://github.com/hirosystems/clarinet/issues/147
=> ci: clarity-js

deno/ext/stacksjs-helper-generator.ts
This PR
* set the argument type to a specific type instead of `ClarityValue`
Still to do: The generated import should reflect the used types. What is the best approach here?
=> Improve argument types

deno/index.ts, examples/simple-nft/.vscode/settings.json, examples/simple-nft/Clarinet.toml, examples/simple-nft/contracts/external/sip-009-nft-trait-standard.clar, examples/simple-nft/contracts/simple-nft.clar, examples/simple-nft/settings/Devnet.toml, examples/simple-nft/tests/simple-nft.test.ts
This PR adds working assertions for all 3 (mint, transfer, burn) NFT events.
I decided to detect events not only based on `assetId` but also `assetAddress`. Same contract can be deployed using different addresses and in such cases using only `assetId` is not selective enough and can give false positive results.
I added example project with simple SIP-009 compliant contract and tests that shows how these new assertions could be used.
=> Feat: add assertions for NFT events

src/generate/project.rs
This PR adds `tasks.json` file generation during new project creation.
Right now generated `tasks.json` file contains only 2 tasks. First executes `clarinet check`, and second one `clarinet test`.
close #154
=> Feat/generate `tasks.json` file

.github/workflows/ci.yaml, .github/workflows/pkg-version-bump.yaml, Cargo.lock, Cargo.toml, src/runnner/deno.rs
In clarity-repl v0.17.0, we updated the type of `result` in the `ExecutionResult` data structure - from String to ClarityValue.
The interface Deno/Rust in Clarinet is still expecting a Clarity value formatted as a string, and was acting strangely in presence of a ClarityValue. This PR is fixing this issue.
=> Compatibility with clarity-repl v0.17.0+

README.md, node-bindings/README.md, node-bindings/lib/index.ts, node-bindings/package.json
This PR is adding a README to the stacks-devnet-js lib and fixing a deployment issue - the `dist` folder should be deployed to NPM, not the `lib`.
=> Tweaks on stacks-devnet-js lib

Cargo.lock, Cargo.toml, src/bin.rs, src/frontend/cli.rs, src/lsp/clarity_language_backend.rs, src/lsp/mod.rs, src/lsp/utils.rs, src/poke/mod.rs
Something that has been in the back of my mind for sometimes now.
With this PR, the idea is to move the Clarity LSP Rust implementation to Clarinet. There are several good reasons to make that move:
- The LSP is clearly a second class citizen today. By moving this feature to this repo, it would become top of mind,
- We want to leverage the amazing pipeline that we have in place in this repo. Apple M1 users are struggling with the LSP, which is something that we solved with this repo, thanks to brew.
- https://github.com/hirosystems/clarity-lsp is going to be re-purposed as a web extension soon, that can be loaded in vscode.dev / github.dev. However, we want to keep this feature available for Vim / Emacs / etc, and Clarinet is a good candidate for hosting this feature.
=> Migrate LSP into clarinet

Cargo.lock, Cargo.toml
fix: rollback to clarity-repl v0.18.0 - it looks like v0.19.0 is not completely ready for prime time.
=> release: v0.21.2

src/types/project_manifest.rs
Implementation of an enhancement described by the issue #174 .
The `clarinet check` feature will show an error message if there is something wrong with the `Clarinet.toml` file:
`Error: there is an issue with the Clarinet.toml file`
=> fail gracefully on Clarinet.toml errors

deno/index.ts
pass the option `only: true` to `Clarinet.test({})` to run only this test
pass the option `ignore: true` to `Clarinet.test({})` to ignore the test
=> feat: added ignore and only options to clarinet test

src/frontend/cli.rs
Using the clarinet application you sometimes get links to documentation that are broken.
Fixed the links to the working ones.
=> fixed links to documentation inside the application

.github/workflows/ci.yaml
Testing a change in the CI script to avoid an error from code-signing in Windows from outside developers.
=> Don't attempt to sign Windows executable on merge to develop

node-bindings/README.md
This PR fixes a typo in the link title and removes unnecessary whitespace from the Readme.
=> fix: link title typo

.github/workflows/ci.yaml, README.md
Since the default branch is `develop`, when users clone the repo, it
will be in this branch by default. This change clarifies in the README
that if they want the latest stable code, they should switch to the
`main` branch.
Add information about updated the deno submodule when pulling into a
previously checked out repo.
Resolves: #231
=> docs: clarify develop vs main branch

src/frontend/cli.rs
After the addition of `repl` in `ProjectManifest` in a5695025, calling
`toml::to_string` on this struct caused a `ValueAfterTable` error. This
problem is handled in the display of the value, so this alternative
method of generating the string avoids the problem.
This is a quick fix, but this code will soon be changed to solve #246.
=> fix: crash on `clarinet new contract`

src/types/project_manifest.rs
In commit cfe7af3a, the new `ProjectConfig` does not serialize the REPL
settings with the correct names to be deserialized later. This struct
gets serialized by `execute_changes`.
=> fix: fix serialization of REPL settings

.github/workflows/pkg-version-bump.yaml
Run `brew update` to avoid conflicts when running `brew bump-formula-pr`. See https://github.com/Homebrew/homebrew-core/pull/95059
=> ci: run brew update prior to bump

examples/billboard/tests/billboard_test.ts
The addresses were hard-coded into the test, and it is not obvious to
new developers where those are coming from. This change uses the account
names to get the addresses instead.
See hirosystems/docs#67
=> docs: improve billboard example

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, node-bindings/package.json
Build `stacks-devnet-js` for linux-x64-musl.
Also fixes https://github.com/hirosystems/clarinet/issues/263
=> feat: stacks-devnet-js support for linux-musl (non-glibc, e.g. alpine)

deno/index.ts
Currently the signature of `expectTuple()` signature is: `expectTuple(): Object;`. So with the following code, TypeScript throws this error: `Property 'str' does not exist on type 'Object'.`
```ts
// test-tuple.clar: (define-read-only (test-tuple) { str: u"hello world" })
Clarinet.test({
name: 'test expectTuple response',
fn(chain: Chain, accounts: Map<string, Account>) {
const { address } = accounts.get('wallet_1')!
const { receipts } = chain.mineBlock([
Tx.contractCall('test-tuple', 'test-tuple', [], address),
])
const tuple = receipts[0].result.expectTuple()
assertExists(tuple.str)
tuple.str.expectUtf8('hello world')
},
})
```
Indeed, `Object` (as in `ObjectConstructor`), does not have a property called `str`.
Possible fixes, `expectTuple` could return:
-  `{ [key: string]: string }` ❌ …
=> refactor: improve "expectTuple" signature

README.md
I think in the releases page only tar.gz available for the binaries
So I create a snippets for people to easily install it
e.g. https://github.com/StackerDAOs/backend/blob/dev/bin/install_clarinet.sh
=> Doc: Use tar.gz in the pre-built binaries install options

src/integrate/orchestrator.rs
Some last minute tweaks: 
- fixing an issue with the explorer not displaying blocks / transactions (devnet is definitely not a 1st class citizen on the explorer side - would be great to get a round of QA there - cc @He1DAr)
- displaying the /doc endpoint in the console, and enabling it (thanks @zone117x @rafaelcr!)
=> fix: adjust some devnet env variables

README.md, src/frontend/cli.rs
- `clarinet deploy` doesn't seem to exist any more, and seems to have been replaced by `clarinet contract publish`
- this PR updates the README + some CLI output to use the updated command
=> docs: change clarinet deploy to clarinet contract publish

src/runnner/deno.rs
This PR introduces new way of presenting execution costs summary.
Cost of each contract is presented in separate table.
fix #133, fix #250
=> fix: incorrect costs synthesis

src/deployment/mod.rs, src/runnner/api_v1.rs, src/runnner/mod.rs
Regression introduced in v0.31.0
To be fixed in v0.31.1
=> fix: code coverage not including initial executions

src/generate/contract.rs
=> fix: use `clarinet@0.31.0` lib in generated tests

src/frontend/cli.rs
When I run the commands in README I get an error eg:
```
$ clarinet deployment generate --mainnet
error: The subcommand 'deployment' wasn't recognized
Did you mean 'deployments' or 'deployments'?
...
```
This commit updates the alias for `deployments` to `deployment` so that these commands work
=> Fix alias for clarinet deployment

src/deployment/mod.rs
When a dependency cannot be found, just ignore it, because the later
analysis will detect it and report a better error message, complete with
proper location information. Also improve the printing of errors from
the ordering of contracts.
See also: hirosystems/clarity-repl#188
Fixes: #396
=> fix: improve error messages about dependencies

README.md, src/frontend/cli.rs
When a file is passed to `clarinet check`, then a syntax-only check is
performed on that one file. A complete check cannot be done when limited
to only one file, since type information for called contracts is not
available.
=> docs: clarify the usage of `clarinet check`

README.md
1. Removed depends_on = [] as it is no longer part of the clarinet.toml file
2. Updated clarinet.toml file config for bbtc.clar and my-contract.clar.
3. Changed the checked contracts to 2 as the default count is 2 contracts.
4. 'clarinet check hiro-coin.clar'  changed to clarinet check <path/to/file.clar> for more clarity.
=> docs: README.md. Removed depends_on() field in the clarinet.toml file and added success message for clarinet check command.

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/lsp/mod.rs, components/clarinet-cli/src/lsp/native_bridge.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/vscode_bridge.rs
@hugocaillard Here is a fix for the native LSP, along with a renaming suggestion (`RequestAsync` -> `Notification` and `RequestSync` -> `Request`, so we stick with the LSP terminology).
Feel free to merge / cherry-pick and update your PR :).
Except for the struct renaming, all the changes won't be impacting your work, and self contained in the `clarinet-cli` component.
=> fix: native lsp

Cargo.lock, components/clarinet-cli/src/deployments/bitcoin_deployment.rs, components/clarinet-cli/src/deployments/mod.rs, components/clarinet-cli/src/integrate/chains_coordinator.rs, vendor/orchestra-event-observer/Cargo.toml, vendor/orchestra-event-observer/src/chainhooks/mod.rs, vendor/orchestra-event-observer/src/main.rs, vendor/orchestra-event-observer/src/observer/mod.rs, vendor/orchestra-event-observer/src/observer/tests/mod.rs
- support for other addresses types in `btc-payment` deployment ops (`p2wpkh` among others, required for lightning)
- ability to receive chainhooks events via `mpsc::channel` - useful when using the `orchestra-event-observer` as a lib
=> Tweaks from hackathon

components/clarinet-files/src/lib.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/state.rs
Avoid showing the full vfs path of a contract in the lsp notifications.
Web
Desktop
Web & Dekstop
`get_relative_location` couldn't be used because it calls `get_project_root_location` that only work on native fs path (not on urls) https://github.com/hirosystems/clarinet/blob/e4c3a4122e13aa7272f46323e54f417cf292f9ec/components/clarinet-files/src/lib.rs#L208
So I took advantage of the `contracts_lookup` prop to retrieve the manifest location.
In the future, we probably want to call more `get_relative_location_from_manifest` and `get_root_location_from_manifest_location` (instead of the non-`from-manifest` ones that call the native FS)
=> fix: cleaner path in lsp notifications

components/clarinet-deployments/src/lib.rs, components/clarinet-files/src/network_manifest.rs, components/clarity-lsp/src/vscode_bridge.rs, components/clarity-vscode/client/src/common.ts, components/clarity-vscode/client/src/customVFS.ts, components/clarity-vscode/package.json, components/clarity-vscode/server/src/common.ts, components/clarity-vscode/test-data/missing-contract/Clarinet.toml, components/clarity-vscode/test-data/missing-contract/settings/Devnet.toml, components/clarity-vscode/web-extension.code-workspace
- Removed the clarity insights options from the config so it's not visible to the users (but the code is still here)
- Fix an issue that make the extension crash when opening a toml file that is not a Clarinet.toml
- Extension won't activate on any toml any way
- Remove useless logs
- Better error message when file is missing
=> fix: few fixes before release the extension

components/clarity-repl/src/repl/session.rs
This was accidentally removed during some merging, and it prevents the debuggers from working.
=> fix: propagate the eval hooks passed to `eval`

components/clarity-repl/src/repl/session.rs
It seems these lines were commented out during the merge and never put back. This simple fix should be all we need.
Fixes: #591
=> fix: fix coverage tracking

.github/workflows/ci.yaml, components/chainhook-types-rs/src/rosetta.rs, components/clarinet-cli/examples/counter/Clarinet.toml, components/clarinet-cli/src/deployments/types.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/runner/api_v1.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-deployments/src/types.rs, components/clarinet-files/src/network_manifest.rs, components/clarity-repl/src/repl/session.rs, components/stacks-rpc-client/src/rpc_client.rs
With this PR, we're adding some new features to deployment plans:
- ability to add `stx-transfer` steps (simnet/devnet/testnet/mainnet)
- better error handling (eliminating the `Generic` error that developers are facing today).
- ability to get costs being computed, using the `v2/fees/transaction` endpoint
=> feat: improve deployment plans

components/clarinet-deno/index.test.ts, components/clarinet-deno/index.ts
Fixes a regression introduced in #618.
Because the "events" array can contain anything (not just the expected event type) events should not be destructured outside of the `try catch`.
Note: further improvements should be expected in `expect<Event>` methods as part of #627 to make error messages easier to understand.
=> Fix: deno expect events

Cargo.lock, components/chainhook-event-observer/Cargo.toml, components/chainhook-event-observer/src/chainhooks/bitcoin/mod.rs, components/chainhook-event-observer/src/indexer/bitcoin/mod.rs, components/chainhook-event-observer/src/observer/mod.rs, components/chainhook-node/Cargo.toml, components/chainhook-node/Chainhook.toml, components/chainhook-node/src/block/digestion.rs, components/chainhook-node/src/block/ingestion.rs, components/chainhook-node/src/cli/mod.rs, components/chainhook-node/src/config/file.rs, components/chainhook-node/src/config/mod.rs, components/chainhook-node/src/lib.rs, components/chainhook-node/src/main.rs, components/chainhook-types-rs/src/bitcoin.rs, components/clarinet-cli/src/deployments/ui/ui.rs, components/stacks-network/src/chains_coordinator.rs, components/stacks-network/src/lib.rs, components/stacks-network/src/orchestrator.rs, dockerfiles/components/chainhook-event-observer.dockerfile
In this PR, we are modifying the developer experience a bit by adding a new mode:
```bash
$ chainhook-node replay --testnet
```
letting developers replay devnet / testnet / mainnet dumps.
I will continue to refactor and tweak the CLI interface in a subsequent PR, but the current approach is already very useful.
=> feat: chainhook-node replay mode

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/generate/contract.rs, components/clarinet-cli/src/lsp/mod.rs, components/clarinet-cli/src/lsp/native_bridge.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-files/src/project_manifest.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/state.rs, components/clarity-lsp/src/vscode_bridge.rs, components/clarity-vscode/client/src/common.ts, components/clarity-vscode/package.json, components/clarity-vscode/server/src/common.ts, components/clarity-vscode/web-extension.code-workspace, components/clarity-vscode/webpack.config.dev.js, components/clarity-vscode/webpack.config.js
Resolves: #630
This PR does not introduce reals changes for Clarity developers, instead it prepares the LSP for #610 and #626 by keeping track of the state of the files being modified (but not saved).
It'll bring nice addition better performances and more reliability by having the editor_state being locked for smaller period of times and less often (thanks @lgalabru for the help on that) with the introduction of
```rust
pub struct EditorStateInput {
editor_state: Option<EditorState>,
editor_state_lock: Option<Arc<RwLock<EditorState>>>,
}
```
~Since the AST is now computed every time a contract is changed, I was able to display diagnostic errors for invalid AST in real time~ I removed it because it overrides other diagnostics (warning and type errors). Will spend more time on that
=> Feat: lsp current editor state

components/clarity-lsp/src/common/hover_data.rs, components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json
The PR also includes a bug fix where clarity 2 contracts wouldn't get documentation for clarity 1 documents
=> chore: bump extension version

components/clarinet-deployments/src/lib.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-vscode/package.json
Address regressions discovered here https://github.com/hirosystems/clarinet/issues/556#issuecomment-1325439110
Fix for Citycoins issue : https://github.com/citycoins/protocol/pull/19#issuecomment-1325431794
This PR reverts a change introduced in https://github.com/citycoins/protocol/pull/19#issuecomment-1325431794
The `manifest.contracts_settings` was introduced because the LSP needed the settings metadata indexed by file location.
But it was necessary to use it in deployments, it even broken it because multiple contracts name can refer to the same file.
Note: I also included a small fix on the LSP e3051c42c375151d907df908f481c307831783a0 (it triggered an error message when clarinet.toml files were opened)
=> fix: use contracts name as index in deployements

components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-deployments/src/types.rs, components/clarity-repl/src/repl/mod.rs, components/clarity-repl/src/repl/session.rs, components/stacks-network/src/chains_coordinator.rs
If an `epoch` is specified for a batch of transactions in the deployment
plan, then this batch will not be deployed until that epoch is live.
Note that the batches are still processed in order, so if a batch that
specifies `2.1` is followed by a batch that specifies `2.05`, that
second batch will run in 2.1.
Example:
```yaml
---
id: 0
name: Devnet deployment
network: devnet
stacks-node: "http://localhost:20443"
bitcoin-node: "http://devnet:devnet@localhost:18443"
plan:
batches:
- id: 0
epoch: 2.05
transactions:
- contract-publish:
contract-name: early
expected-sender: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
cost: 830
path: contracts/early.clar
anchor-block-only: true
- id: 1
epoch: 2.1
transactions:
- contract-publish:
contract-name: test
expected-sender: …
```
=> feat: Add `epoch` field to batch in deployment plans

components/clarinet-cli/src/runner/api_v1.rs
This allows contract deploys to work in Clarinet tests. Without this, a contract deploy tx would hit the `unreachable` branch.
Here's a simple Clarinet test that works if you use this branch:
```ts
// A simple test for fixing the `deployContract` tx type in Clarinet
import { Clarinet, Tx } from 'https://deno.land/x/clarinet@v1.0.3/index.ts';
Clarinet.test({
name: 'deploy a contract',
fn(chain) {
const deployer = 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM';
const contractName = 'contract';
const src = '(define-read-only (test-fn) u123)';
chain.mineBlock([
Tx.deployContract(contractName, src, deployer),
]);
const receipt = chain.callReadOnlyFn(contractName, 'test-fn', [], deployer);
receipt.result.expectUint(123);
},
});
```
=> fix: support contract deploys in runner

components/clarity-vscode/package.json
My bad, "1.3.0" shouldn't have make it to develop, this version was never released.
Version "1.1.0" was the pre-release and "1.2.0" has been released to VSCE and OVSX
=> chore: update clarity-vscode version

components/clarinet-cli/src/runner/api_v1.rs, components/clarinet-files/src/project_manifest.rs, components/clarity-repl/src/bin.rs, components/clarity-repl/src/lib.rs, components/clarity-repl/src/repl/boot/costs-3.clar, components/clarity-repl/src/repl/boot/mod.rs, components/clarity-repl/src/repl/session.rs
This is a fix for #709 - check out that issue for more details and a repro of the bug.
This PR does two things:
- Adds `costs-3` boot contract
- I pulled the code in from `stacks-blockchain` and added it to various "default boot code" places, including in the project manifest
- When making a `contract-call?` in `clarity-repl`, I set the epoch to 2.1.
The latter fix was the only thing that actually fixed the issue. The exact line of code is here: https://github.com/hstove/clarinet/blob/0ca1d66cb47e39763061a9017f7e45771938c896/components/clarity-repl/src/repl/session.rs#L593 . Without this line, my issue still fails.
One thing I noticed, via some debugging, was that my contract was being added to the Clarity DB with epoch "2.0" in tests, even though I have it specified as 2.1 in my …
=> fix contract calls into clarity2 contracts

components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/types.rs, components/clarity-repl/src/repl/session.rs
This PR is completing https://github.com/hirosystems/clarinet/pull/711 which was addressing https://github.com/hirosystems/clarinet/issues/709.
It essentially introduce a `session.currentEpoch` that developers (or deployment plan executor) can update for executing Clarity 2 snippets.
We're using 2.05 as a default epoch.
=> feat: ability to set_epoch in repl

components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/requests/definitions.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/analysis/ast_visitor.rs, components/clarity-vscode/package.json
Fix: #725 
The first commit (39867c26e130ddc70aaf8e074e0f865f86cfd965) add go to definition for map, filter and fold methods.
The second one (26c72d44ca62104ff79a9e966543597a69944804) makes safer access to params in ast visitor.
=> Fix: go to definition iterators

Cargo.lock, components/clarity-lsp/Cargo.toml, components/clarity-lsp/src/common/backend.rs, components/clarity-repl/src/analysis/ast_visitor.rs, components/clarity-vscode/client/src/common.ts, components/clarity-vscode/package.json, components/clarity-vscode/server/src/common.ts
Follow up for #728.
Fix more unsafe access to Slice in AST Visitor.
Plus: allow to disable/enable some LSP features
=> fix: safe access to define function params

components/clarity-repl/src/repl/session.rs
Fix #477
Added support, in the clarity-repl, for a new command called `keywords`. That command returns the keywords from the Clarity language.
Below some screenshots with the new command and it's usage.
Thanks.
=> Add keywords command

components/clarinet-files/src/network_manifest.rs, components/stacks-devnet-js/lib/index.ts, components/stacks-devnet-js/src/lib.rs, components/stacks-network/src/orchestrator.rs
Improving the best effort to use docker:
- use the socket path specified in the config or use a default path
- use docker defaults settings
- try to use the socket eventually living in `/Users/<name>/.docker/run/docker.sock`
=> fix: docker socket handling

components/clarity-repl/src/repl/session.rs
Hello!
This PR adds a column with percentage information when running ::get_costs command. And also fix a `panic!` issued by the repl.
Related issues:
#461 
#745
=> Add percentage on ::get_costs command output

components/clarity-repl/src/repl/boot/pox-2.clar
The current pox-2 contract embedded in Clarinet is not the latest version (thanks @philipdesmedt).
Tested against https://github.com/arkadiko-dao/arkadiko/pull/532.
=> Fix: update pox-2

components/clarinet-cli/src/generate/contract.rs
This updates the default template for contracts created with `clarinet contract new` based on the discussion in #730.
In the PR `synopsis` was changed to `summary`, but everything else is the same.
An example of the output after building locally is below:
```bash
> clarinet contract new fancy-contract
Created file contracts/fancy-contract.clar
Created file tests/fancy-contract_test.ts
Updated Clarinet.toml with contract fancy-contract
> cat contracts/fancy-contract.clar
```
```clarity
;; title: fancy-contract
;; version:
;; summary:
;; description:
;; traits
;;
;; token definitions
;; 
;; constants
;;
;; data vars
;;
;; data maps
;;
;; public functions
;;
;; read only functions
;;
;; private functions
;;
```
One thought was to add a suggestion to each item to explain it's usage, but I …
=> Update default Clarity template for new contracts

components/clarity-repl/src/repl/session.rs
Fix #738 .
And, when reviewing, also please check if the command wording/spelling is ok.
Cheers!
=> fix: missing commands help information

components/clarinet-deno/index.ts
If you call `expectPrintEvent`, and there are other types of events before the print, then an error will be logged. This warning clutters the logs and made me think the test was failing.
=> fix: remove warning in `expectPrintEvent`

components/clarinet-cli/examples/billboard/Clarinet.toml, components/clarinet-cli/examples/cbtc/Clarinet.toml, components/clarinet-cli/examples/counter/Clarinet.toml, components/clarinet-cli/examples/counter/contracts/counter-v2.clar, components/clarinet-cli/examples/counter/tests/counter_test.ts, components/clarinet-cli/examples/simple-nft/Clarinet.toml, components/clarinet-cli/src/lsp/mod.rs, components/clarinet-deployments/src/lib.rs
It looks like the latest clarity vm fixed an issue related to the epoch handling that requires some updates in clarinet.
Adding a clarity 2 contract in the counter example should help us catching eventual future regressions.
=> fix: update epoch handling 

Cargo.toml
This PR adds a missing component `clarity-repl` to the main `Cargo.toml` file. The list of components is also re-organized in an alphabetically order.
This PR can be also used to check if the issue #462 is still relevant. If the CI runs automatically, that issue can be closed.
=> fix: add clarity-repl component

components/chainhook-node/src/cli/mod.rs
This patch is addressing an issue where a chainhook-node receiving a predicate registration before the first ingestion, would cause a crash.
=> fix: avoid devnet crash

components/clarity-repl/src/repl/tracer.rs
There is a placeholder expression ID inserted for the top-level
instruction which was previously set at 0. It seems that an expression
can have ID 0 during normal evaluation, so instead, use `u64::MAX`.
=> fix: avoid expression ID conflict

components/clarity-repl/Cargo.toml, components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json
This PR contains the version bump of the vscode extension and some npm dependencies minor upgrade.
The v1.4.1 has already been released manually with a local build (based on a local version of the clarity-vm).
=> Chore/vscode/release 4.1.0

docs/feature-guides/clarinet-deploy.md
Without it, I run into the following errors when compiling docs. 
>SyntaxError: /Users/sabbyanandan/hiro/docs/docs/clarinet/feature-guides/clarinet-deploy.md: Expected corresponding JSX closing tag for <br>. (24:267)
22 | <tr parentName="tbody">
23 | <td parentName="tr" {...{"align":null}}>{`publish contracts`}</td>
> 24 | <td parentName="tr" {...{"align":null}}>{`- deploy a contract to an in-memory simulated Stacks chain or an integrate Stacks-Bitcoin environment `}<br>{` - deploy to a public testnet or mainnet `}<br>{` - deploy an external contract to your local network for testing`}</td>
| …
=> Close BR tags to resolve docs compilation error

docs/feature-guides/clarinet-deploy.md
Fixed broken link to the How-to deployment plans documentation.
=> Fixed broken link in the Clarinet-deploy documentation

components/clarity-lsp/src/common/state.rs, components/clarity-repl/Cargo.toml, components/clarity-vscode/test-data/simple/Clarinet.toml, components/clarity-vscode/test-data/simple/contracts/counter.clar, components/clarity-vscode/test-data/test-cases/Clarinet.toml
The issue was that contracts with no analysis (so empty contracts or contracts with no functions defined) would default to `CLARITY_DEFAULT_VERSION`.
This default value would then be cascaded to the `active_contract_metadata` (for contracts currently opened in the editor) [here](https://github.com/hirosystems/clarinet/blob/develop/components/clarity-lsp/src/common/state.rs#L247-L249). Thus, ignoring the version specified in the manifest
=> Fix: lsp: better handling of clarity version

docs/feature-guides/clarinet-deploy.md
This change adds Max's new long form video walkthrough to the feature guide on deployment plans.
=> Add Max's Deployment Plans Video to References

components/clarinet-cli/src/generate/contract.rs
These ideas come from @whoabuddy and the CityCoins project. The TODO
assertion adds a nice visual reminder to add new tests if the user runs
`clarinet test` with the default tests. The "arrange, act, assert" is a
nice pattern for organizing these tests.
=> test: improvements to the generated unit tests

components/clarity-repl/src/repl/debug/dap/mod.rs
Hello! Really cool project, thanks for this! This is seemingly the only DAP adaptor implementation written in Rust (at least according to sourcegraph)!
AFAICT clarinet has implemented the DAP adapter communication layer.  Unfortunately, the `DebugAdapterCodec` struct is private. Would yall be willing to make it `pub` so I can depend on it? I'm trying to write an [adapter](https://github.com/DieracDelta/nix-debug-adapter), and specifically that codec is quite useful 😅 
It would actually be really great if that codec file was its own (admittedly small) crate. That way much less dependencies would be brought in for other dap adaptors written in rust.
=> Make debug codec module public

docs/faq.md
Added clarinet integrate FAQ to find the location of logs for clarinet integrate command.
=> Clarinet docs: FAQ - Added FAQ for clarinet integrate logs

components/clarinet-cli/src/frontend/cli.rs
```
$ clarinet completions bash
thread 'main' panicked at 'crate::generate should have set the bin_name', /Users/brice/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_complete-3.2.5/src/shells/bash.rs:17:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix: resolve panic when generating completions

Cargo.lock
Upgrade dependency to fix audit (and CI)
=> Upgrade h2 to fix RUSTSEC-2023-0034

components/clarinet-deployments/src/lib.rs
Fix #980 
In case of circular dependency in unknown dependencies, like there is between [.alex-vault](https://explorer.hiro.so/txid/0x68e84359d36530fb71b47573796a4732651dcc5b766d2818e6f6b3e3d593e3e4?chain=mainnet) and [.fixed-weight-pool](https://explorer.hiro.so/txid/0x608734b7a5b09f90780ebd8a141f3254e5c06ea160c27c7f5157d50236a6cf90?chain=mainnet), we run into an infinite loop to handle requirements. 
The issue says that it used to work before, but I wasn't able to find at which point we broke it.
This is a naive implementation to patch it
=> fix: circular dependencies in deployments

Cargo.lock, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/datastore.rs
`std::time` is not available in the browser.
It was introduced in https://github.com/hirosystems/clarinet/pull/963
`panicked at 'time not implemented on this platform'`
We missed the error because it happens at runtime (and not at compile time)
=> fix: default genesis time to 0 in wasm

components/clarinet-deployments/src/lib.rs, components/clarity-repl/src/analysis/ast_dependency_detector.rs, components/clarity-repl/src/repl/interpreter.rs
In Clarity 1 it was possible to have duplicated functions in trait declarations. It now illegal in Clarity 2.
But when requiring a trait from mainnet that does exploit this bug, clarinet has to handle it.
In the dependency detector, we thought it would be safe to default to Clarity2 for requirements. In this case (requiring a trait with duplicated function), it isn't.
Ideally, we'll want to do the same the EPOCH (avoid default epoch in dependency detector) (to be done in this PR or a future one)
This PR also revers the changes from #985
=> fix: handle clarity-version in the dependency detector

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarity-jupyter-kernel/Cargo.toml, components/clarity-lsp/Cargo.toml, components/clarity-lsp/src/common/requests/capabilities.rs
v1.6.0 fails to build on macOS 12 arm due to error "fail compiling rand_pcg v0.1.2" 
See [logs](https://github.com/Homebrew/homebrew-core/actions/runs/4973621006/jobs/8899767478?pr=130963#step:3:1431) and PR: https://github.com/Homebrew/homebrew-core/pull/130963
`rand_pcg@0.1.2` was a deep dependency of tower-lsp and cargo wouldn't update just rand_pcg. So I took the opportunity to upgrade tower-lsp (and lsp-types) in this PR.
The upgrade of uuid@1.0.0 in clarinet-jupyter-kernel is not necessary to fix the build but it was also referencing `rand-pcg@0.1.2` and I wanted to fully remove it
=> Chore: upgrade lsp dependencies

.gitignore, Cargo.lock, README.md, components/clarinet-cli/Cargo.toml, components/clarity-repl/src/analysis/coverage.rs, components/clarity-repl/src/analysis/coverage_tests.rs, components/clarity-repl/src/analysis/mod.rs, docs/how-to-guides/how-to-test-contract.md
Fix: #991 
Rework test coverage to:
- handle code branches
- fix line hit count: a line with N expressions hit one time would be counted as N hits (instead of 1)
- fix `match` coverage: bindings were considered as executable lines
Code branching takes into account `if`, `asserts!`, `match`, `and`, `or`
=> feat: improve clarity test code coverage and handle code branches

.github/workflows/pkg-version-bump.yaml
As we are currently investigating CI issues on the homebrew side that we fail to reproduce anywhere else, I'd like to have this `force` flag. Afaik it only forces PRs even if we already have one opened on the homebrew-core repo (which can be detected as duplicated). 
Note: The 2 other lines are automatic formatting
=> ci: force brew bump formula

Cargo.lock, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/mod.rs
The PR reverts the usage of clarity vm 2.1 and clarity-repl 1.6.4 in order to fix the develop branch
clarity-repl has been published on crates.io but it shouldn't be on develop, since it's currently breaking other components.
This change will be re-applied on #978 that is fully compatible with clarity vm 2.1.
=> chore: revert clarity vm 2.1

Cargo.lock, components/clarinet-cli/src/chainhooks/mod.rs, components/stacks-rpc-client/Cargo.toml, components/stacks-rpc-client/src/crypto.rs, components/stacks-rpc-client/src/lib.rs
In this PR, we are moving some code to the stacks-rpc crate.
Ultimately we get rid of all the on chain logic present in the deployment plan crate (onchain.rs), and have deployment plans relying on this lib instead.
=> refactor: better stacks-rpc crate

README.md, docs/getting-started.md
@LakshmiLavanyaKasturi  I added the same note in the readme and in the docs.
The idea is simply to explain that we need some time and effort to be able to release the latest and futures versions of Clarinet on homebrew.
And link to the alternative solutions (which is to download the binary and install it).
Let me know what you think
=> docs: homebrew release warning

CHANGELOG.md
We used to have level 1 heading for version numbers and I find it more readable.
I put the links as it used to be done as well
=> docs: format changelog

components/clarinet-cli/src/frontend/cli.rs
Add `--allow-read` to `clarinet test` subcommand in order to allow filesystem reads in tests. This allows us to share configuration between tests by reading data from JSON/YAML files.
=> feat: Add `--allow-read` flag to allow filesystem read access in `clarinet test`

components/clarity-repl/src/repl/datastore.rs
Fix: #1043 
The fix prevent the crash.
At the clarinet level, it's not really feasible to catch this error and return an error or warning on the diagnostic.
=> fix: repl: panic at get_current_block_height for unexisting block

README.md
When trying to build `clarinet` via `cargo` on `ubuntu-22.04`, the build fails as per #1066 
The problem is that `README.md` doesn't specify `curl` or `python` as a dependency, and it isn't installed by default.  So this PR just adds `curl` to the `apt get` line in `README.md`.  
Fixes #1066
=> Add curl to the apt get line in README.md

components/stacks-network/src/orchestrator.rs
This PR fixes the faucet integration when running the local devnet. During devnet orchestration, the stacks-blockchain-api was not provided the faucet secret key for the faucet defined in Devnet.toml. This PR addresses this by adding the `FAUCET_PRIVATE_KEY` environment variable to the `env` used to launch the docker container.
=> Bug: fix stacks-blockchain-api faucet integration

components/clarity-repl/src/repl/mod.rs
When a new contract is added with `clarinet contracts new`, this will set the epoch to `2.4` instead of the current `2.1`.
=> chore: update default epoch to 2.4

components/clarity-repl/src/analysis/coverage.rs
Fix: #768 
Invalid line number in lcov files (<= 0) can break some coverage renderers (such as the Coverage Gutters extension mentioned here https://github.com/hirosystems/clarinet/issues/1062).
This PR doesn't fix the root cause (we shouldn't have executable line with a span start at line 0) but at least it prevents the renderers to crash. The root cause should be fixed at the VM level (some cases have already been fixed in the past https://github.com/stacks-network/stacks-blockchain/pull/3421) 
/
/
---
/
=> fix: safety check on invalid line number in coverage

components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json
This is the vscode release
I published 1.7.1 as a pre-release
=> chore: bump vscode extension to 1.7.2

components/clarity-repl/src/repl/session.rs
Fix: #1011 
The clarity-repl command ::get_costs works with commands such a `42` but when there is a space, in commands such as `(+ u1 u1)`, an error comes.
=> fix: get_costs analyzes commands with spaces

docs/feature-guides/clarinet-deploy.md
Edit typos and language fixes in the 'Clarinet Deployment Plans' doc
- **Please note**: Noticed the text `chain transactions` in the `call contract functions` row in the `Deployment plan primitives` table. Suggested removing it since it did not seem relevant in the context of that sentence.
No
=> Edit typos and language fixes in the 'Clarinet Deployment Plans' doc

docs/introduction.md
Grammatical fixes in the Introduction file
No
=> Fix grammar related issues in the Introduction file

.github/workflows/ci.yaml, dockerfiles/components/clarinet-dev.dockerfile, dockerfiles/components/clarinet.dockerfile, rust-toolchain
The recent issue in the CI is caused by the fact that our version of v8 doesn't build with the latest rustc version (1.72.0 that became the stable release 2 weeks ago).
Let's fix the version to 1.71.0 (latest version able to build clarinet) both in the CI and locally (rust-toolchain file).
In the future, I think we should always use stable (both in CI and locally).
This will be possible once we remove deno and v8 from the dependencies (in the coming weeks)
=> ci: use rust toolchain v1.71.0

Cargo.lock, components/clarinet-deployments/Cargo.toml, components/clarinet-deployments/src/types.rs
The WASM build broke with #1116
This is a naive fix proposal
Note: the wasm build will be checked in the upcoming version of the CI
=> fix: clarinet-deployments wasm build

components/clarinet-cli/src/frontend/cli.rs
The user prompt to confirm a `clarinet deployments apply` makes it hard to use in automated scripts. Adding an option '-y' to pre-accept the deployment would allow users to automate deployments.
=> deployment apply -y option

README.md, docs/feature-guides/extend-clarinet.md, docs/how-to-guides/how-to-test-contract.md
Fix: #1149
Very basic deprecation warning for `clarinet run` and `clarinet test`
=> docs: deprecation warnings for clarinet test and clarinet run

components/clarinet-sdk/README.md, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/src-ts/bin/index.ts, components/clarinet-sdk/src-ts/bin/templates/package.json, components/clarinet-sdk/src-ts/bin/templates/tests/contract.test.ts, components/clarinet-sdk/src-ts/bin/templates/tsconfig.json, components/clarinet-sdk/src-ts/bin/templates/vitest.config.js, components/clarinet-sdk/tsconfig.base.json, components/clarinet-sdk/webpack.config.dev.js, components/clarinet-sdk/webpack.config.js
This bin script will allow to create the necessary boilerplate to use the clarinet-sdk testing framework in existing clarinet projects.
Usage
```sh
npx @hirosystems/clarinet-sdk
```
Note: it won't be needed in projects generated with clarinet 2.
@ryanwaits Adding you as a reviewer for the change in the Readme (still very basic doc but more to come soon)
=> feat: create clarinet-sdk testing boilerplate

Cargo.lock, components/clarinet-sdk/.prettierrc, components/clarinet-sdk/Cargo.toml, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/src-ts/bin/index.ts, components/clarinet-sdk/src-ts/contractAst.ts, components/clarinet-sdk/src-ts/index.ts, components/clarinet-sdk/src-ts/vfs.ts, components/clarinet-sdk/src/core.rs, components/clarinet-sdk/tests/index.test.ts
Slightly change the Rust Struct of `SDK` to hold the whole contracts analysis (instead  of `contracts_sources: Hashmap, contract_asts: Hashmap` etc.
The `ContractAST` typescript type is still very basic (can't easily be transform from Rust to TypeScript because of cyclic properties) and can be greatly improved. For now, I wanted to have to recursive nature of `expr.List`.
The project with missing a prettier config so the formatting could get inconsistent. Add one.
=> feat: sdk: get contract ast

components/clarinet-sdk/src/index.ts, components/clarinet-sdk/tests/index.test.ts
Clarity event values should be transform to Stack.js values just like contract call responses
=> fix(sdk): deserialize events values as clarity values

components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/src/vitest/index.ts, components/clarinet-sdk/templates/package.json, components/clarinet-sdk/vitest-helpers/src/global.d.ts, components/clarinet-sdk/vitest-helpers/src/vitest.setup.ts
I used to generated both coverage and costs reports file only with the `--coverage` option. It's now split between `--costs` and `--coverage`
=> Feat: add a --costs flag in the tests framework

components/stacks-network/src/orchestrator.rs
[This PR](https://github.com/hirosystems/stacks-devnet-api/pull/65) on the stacks devnet api renames some services. This updates the clarinet image to point to the correct service urls so it can properly coordinate chain progress.
=> chore: update service names for k8s devnet assets

components/clarinet-sdk/README.md, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/src/index.ts, components/clarinet-sdk/templates/tests/contract.test.ts, components/clarinet-sdk/tests/index.test.ts, components/clarinet-sdk/vitest-helpers/src/global.d.ts, components/clarinet-sdk/vitest-helpers/src/vitest.setup.ts
In the the clarinet-sdk, the naming `vm` as in `initVM` and `ClarityVM` where never satisfying. But we kept it lacking better alternative.
After talking with Ludo, we agreed that `simnet` was a better option
- it'll explicit tell developers what the `simnet` (it's basically what you interact with when using the SDK)
- it's not super intuitive, but `vm` wasn't either
- `simnet.mineBlock()` makes wayyy more sense than `vm.mineBlock()` (which doesn't make any)
This PR only changes the JS layer since the rust code doesn't make any mention of the `VM` wording in this context.
The Rust layer (components/clarinet-sdk-wasm) exposes a SDK constructor (which could be improved but is kind of okay. And isn't visible to end user since it's abstracted by the JS layer). It exposes an `init_session` …
=> refactor(sdk): rename vm to simnet

.github/workflows/audit-format.yaml, .github/workflows/ci.yaml, Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarity-jupyter-kernel/Cargo.toml, components/clarity-repl/Cargo.toml, components/stacks-network/Cargo.toml
Most audit "ignores" were need by deno/v8, removed it and update a few other dependencies
=> chore: update cargo dependencies and audit

components/clarinet-cli/src/generate/contract.rs
fixes #1031 by replacing `.` with `_` in contract file names
N/A
---
If there are applicable tests to add, I'm glad to do that. I was unable to find them tho, so I added the screenshots above
=> replace . with _ for contract names

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/Cargo.toml, components/clarinet-deployments/src/diagnostic_digest.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/src/index.ts, components/clarinet-sdk/tests/fixtures/InvalidManifest.toml, components/clarinet-sdk/tests/fixtures/contracts/invalid.clar, components/clarinet-sdk/tests/index.test.ts, components/clarinet-sdk/vitest.config.js, components/hiro-system-kit/src/macros.rs
Fix: #1191 
- On simnet init, throw an error if the contracts are invalid (ie: there is at least one error in diagnostic)
- While working on the test, I found another error, because of the way I handled the cache, we couldn't load two sessions. This is fixed as well by this PR
=> fix(sdk): throw error if invalid deployments

components/clarity-repl/src/repl/session.rs
fix: #1164 
- deploy_contract now returns an Err if it's called with Clarity v2 and Epoch 2.0
=> fix(sdk): Epoch and clarity version mismatch

.vscode/settings.json, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/generate/chainhook.rs, components/clarinet-cli/src/generate/contract.rs, components/clarinet-cli/src/generate/project.rs
Generate the right file to use the clarinet-sdk for test.
In this PR, I also slowly started to implement cargo `clippy` instead of `check`
=> feat: update clarinet generated template to use the sdk

components/clarinet-deployments/src/lib.rs, components/clarinet-sdk-wasm/src/core.rs, components/clarity-repl/src/analysis/ast_dependency_detector.rs
A dependency to a contract can exist in a constant.
eg:
This type of dependency wasn't detected before
```clarity
(define-constant abtc-token .token-abtc)
(define-public (test)
(try! (contract-call? abtc-token ...))
)
```
=> fix: detect dependencies defined in const

components/clarity-repl/src/analysis/coverage.rs, components/clarity-repl/src/analysis/coverage_tests.rs
The first argument of `map`, `filter` and `fold` doesn't trigger `will_eval_hook`. Leading to false negative in coverage reports.
But it's safe to assume that this expr is hit of the map, filter or fold is hit as well.
=> fix: missing coverage in clarity iterator functions

components/clarinet-cli/src/frontend/clarinetrc.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/frontend/mod.rs, components/clarity-repl/src/repl/debug/cli.rs
Follow up #1208 
@tippenein I might have approved your previous PR a bit too quickly.
In your implementation, if telemetry is disabled globally, it would still ask for each project to enable telemetry Y/n, while i think it shouldn't.
I took this liberty to work on the follow-up PR to make sure we can ship it in 2.0 👌 
I also updated the setting file to be `~/.clarinet/clarinetrc.toml`, this way, we can more easily provide a json schema file for it in the future if we want to (vs `Settings.toml` that seems to generic)
This PR also updates the hints messages
Fixes: #205
=> refactor: improve global settings management

.github/workflows/ci-clarinet-cli.yaml, .github/workflows/ci.yaml, codecov.yml
=> ci: add coverage

components/clarinet-cli/src/generate/project.rs
=> fix: remove extra { in tasks.json

.github/workflows/ci.yaml
Fix regression introduced in https://github.com/hirosystems/clarinet/pull/1258
=> ci: fix devnet rustc version hash

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/frontend/cli.rs, components/clarity-events/Cargo.toml, components/stacks-network/Cargo.toml
In an effort to keep the project dependencies updated, upgrade clap to the latest version.
- `clap_generate` has been renamed to `clap_complete`
- `conflicts_with` now takes the actual property name (not the `long` form)
- re-arranged a bit the enums and macros (for aliases)
- make everything slightly more consistent
I removed the deprecated `Test` and `Run` commands, it's a bit early bit I'm quite in a quest to remove as much dead code as I can on the repo
=> chore: ugprade clap

components/clarinet-sdk/README.md
The clarinet-sdk requires a few steps to be built and tested locally. While this should be improved in the future, let's explain the steps in the readme
=> docs: improve clarinet-sdk contributing section

components/clarinet-cli/src/deployments/ui/ui.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-files/src/network_manifest.rs
Address:
https://github.com/hirosystems/clarinet/issues/1129
https://github.com/hirosystems/clarinet/issues/1235
=> fix: polish deployment ux

Cargo.lock, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json
Just a version bump to release clarinet-sdk-wasm (and clarinet-sdk), to include #1273
=> chore: bump clarinet sdk version

components/clarity-repl/src/repl/interpreter.rs
There was a `transient` address being used here from early experimentation that needed to be replaced with the appropriate principal.
=> Fix `tx sender` in Clarity-Wasm contract calls

dockerfiles/devnet/Bitcoin.dockerfile
This PR updates Bitcoin image to 26.0.
~It also removes the wallet support that seems needless for Clarinet use case.~
Fixes: #1305
=> update bitcoin image to 26.0

Cargo.lock, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/lib.rs, components/clarity-repl/src/analysis/call_checker.rs, components/clarity-repl/src/analysis/check_checker/mod.rs, components/clarity-repl/src/bin.rs, components/clarity-repl/src/frontend/terminal.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, components/clarity-repl/src/repl/settings.rs
Revamp the way we run the clarity-wasm preview in `clarinet console` . We now run two session in parallel, the second one run in "wasm-mode".
- The second session (the wasm one), can be **disabled** with: 
```console
clarinet console --disable-clarity-wasm
```
- If the interpreter and clarity-wasm return different results, the results are logged and a message asks the users to open an issue
- These PR also implements a `::toggle_timings` that give an approximate idea of how long a snippet execution took
=> feat: run clarity-wasm in a separate session

README.md
In the latest version `clarinet test` is deprecated in favor of using the Clarinet SDK for unit testing.
The default steps in the README now will fail because `clarinet test` does not run, see below:
https://github.com/stacks-m2m/contracts/actions/runs/7661218176
By updating the steps to use `clarinet check` first, then install Node + run `npm test`, this version is more in line with the default setup and succeeds:
https://github.com/stacks-m2m/contracts/actions/runs/7661309610
This also updates the checkout and codecov actions to their latest versions.
You can see the file we're using here which is very similar:
https://github.com/stacks-m2m/contracts/blob/main/.github/workflows/clarinet.yml
=> Update Github action format for Clarinet 2.x

components/clarinet-cli/src/frontend/cli.rs
Update docs url in hint messaging
=> update docs url in messaging

Cargo.lock, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/src/contractInterface.ts, components/clarinet-sdk/src/index.ts, components/clarinet-sdk/tests/index.test.ts, components/clarity-repl/Cargo.toml, components/clarity-repl/src/lib.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs
- Update clar2wasm and clarity to get the wasm compiliation fixes
- Make wsts optional
- Don't use std::time in wasm
- Some code was lost during a previous (get_block_time)
=> fix wasm build

components/clarity-repl/Cargo.toml, components/clarity-repl/src/lib.rs
Fix regression
The stacks-rpc-client build was broken, because it requires the repl with no-default-features and the feature `sdk`
https://github.com/hirosystems/clarinet/blob/develop/components/stacks-rpc-client/Cargo.toml#L23-L25
I broke it in #1295 by making wsts optional for "wasm" and forgot to include it in "sdk"
Also need to create an issue check the stacks-rpc-client build status in CI
=> fix: clarity repl build (sdk)

Cargo.lock, components/clarinet-files/Cargo.toml, components/stacks-network/Cargo.toml
Chainhook was based on a clarinet branch that no longer exists (chore/upgrade-clarity-vm)
This PR update the chainhook depedendencies
=> chore: upgrade dependencies

components/clarity-repl/Cargo.toml
By [fixing stacks-devnet-js build](https://github.com/hirosystems/clarinet/commit/5b3fdb8a9e686d060ff1da71c5f4ae879f001f39#diff-9afcfd70da92c34f20b65f2c5bd9920d157a54178212aea763c971afe651f78bR60) yesterday, I un-fixed the clarinet-sdk build [fix I made 2 days ago](https://github.com/hirosystems/clarinet/commit/8d8ea7fd2bc3b7d2132431ec01eac751978aa795#diff-9afcfd70da92c34f20b65f2c5bd9920d157a54178212aea763c971afe651f78bR60)
wsts needs to be optional = true AND default-feature = false
=> fix: wasm build

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-files/Cargo.toml, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, components/stacks-network/Cargo.toml, components/stacks-network/src/chains_coordinator.rs
- Fixes #1349 
- Include boot contracts in the session when using --enable-clarity-wasm (for both `console` and `check` 
- update clarity-wasm (including a bug for bns.clar)
```sh
$ clarinet check --enable-clarity-wasm
```
=> feat: enable clarity-wasm in clarity check

components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/types.rs
In clarinet console, we are already doing a complete comparison of the interpreter vs wasm results and diags ([see code](https://github.com/hirosystems/clarinet/blob/abc3458515f890aeee51cfb376e00eadd76dda7c/components/clarity-repl/src/frontend/terminal.rs#L135-L178).
But it wasn't the case for contract deployments (in clarinet check or clarinet console).
This PR fixes it.
It also improves the handling of project with multiple contracts.
The contract will result in a compile error in clarity wasm:
```clar
(define-map mp {x: uint} {y: (list 20 (response (buff 21) int)) })
(map-insert mp
{x: u306845443603200851488318099 }
{y: (list
(ok 0xac50891b72b93b496d25caedc508e9f65b98727ee6)
(ok 0x53f588bdbb3495aee902cdaa863d31e2dc42b8215d)
(ok 0xccc90ca2258d144e11cd32c453599bd36d039120e6)
(ok …
```
=> feat: improve clarity wasm deployment comparison

components/clarinet-cli/src/devnet/start.rs, components/clarinet-cli/src/frontend/cli.rs, components/stacks-network/src/chains_coordinator.rs, components/stacks-network/src/event.rs, components/stacks-network/src/lib.rs, components/stacks-network/src/ui/mod.rs
=> fix: remove errors on exit when running devnet with `--no-dashboard`

components/clarinet-sdk/templates/package.json, components/clarinet-sdk/templates/vitest.config.js
Update the package.json and vitest.config 
- clarinet-sdk and vitest-environment-clarinet versions to be released
- the vitest `pool: "forks"` option seems to be more stable (and I didn't notice significant decrease of performances). The previous version doesn't apparently lead to issues very often, but could do. According to the [documentation,](https://vitest.dev/guide/common-errors.html#failed-to-terminate-worker), it could be do to the fact the `clarinet_sdk_bg.wasm` file is fetched with node `fetch` 
---
=> chore: update clarinet project template

CHANGELOG.md, Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/generate/project.rs, components/clarinet-deployments/Cargo.toml, components/clarinet-files/Cargo.toml, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/templates/package.json, components/clarity-repl/Cargo.toml, components/stacks-devnet-js/Cargo.toml, components/stacks-devnet-js/package.json, components/stacks-network/Cargo.toml, components/stacks-rpc-client/Cargo.toml
- CLI: Update the vitest template (used in `clarinet new`) to fix the thread issue
- SDK: Update the contracts path in deployment plan to be relative instead of absolute
- Upgrade cli to 2.3.1
- Upgrade SDK to 2.3.2
=> chore: prepare 2.3.1

.cargo/config, Cargo.lock, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk-wasm/src/utils/mod.rs, components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json, components/clarinet-sdk/src/index.ts, components/clarinet-sdk/tests/fixtures/contracts/counter.clar, components/clarinet-sdk/tests/simnet-usage.test.ts, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/clarity_values.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/mod.rs, components/clarity-repl/src/repl/session.rs
Fix: #547 
Allow to contract private functions from the simnet.
It requires the changes of this PR https://github.com/stacks-network/stacks-core/pull/4520, which have been cherry-picked on feat/clarity-wasm-next.
In the interpreter, there's a new `call_contract_fn` method that can be used instead of `run` or `execute` to perform contract calls.
This method is slightly more performant (it doesn't build an virtual contract and has a better clarity args serialization logic).
This improved way to all contract functions is now used for `callPublicFn` and `callReadOnlyFn` as well
---
=> feat: call private function in simnet

components/clarity-repl/src/repl/boot/mod.rs, components/clarity-repl/src/repl/boot/signers-voting.clar, components/clarity-repl/src/repl/boot/signers.clar, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs
=> feat: add signers and signers-voting boot contracts

components/clarinet-sdk/package-lock.json, components/clarinet-sdk/package.json
Update @hirosytems/clarinet-sdk version (for the manual release on npm)
=> chore: bump clarinet-sdk version to 2.4.1

Cargo.lock, components/hiro-system-kit/Cargo.toml, components/hiro-system-kit/src/log/mod.rs
Chainhook needs a debug log level that still uses slog_json when built in release mode. This PR adds a new feature to accomplish this.
Additionally, Grafana has set [log levels](https://grafana.com/docs/grafana/latest/explore/logs-integration/#log-level) that it uses for parsing logs. Currently the devops team has [custom patches](https://github.com/hirosystems/chainhook/pull/524#issuecomment-2023392097) to support parsing logs from hiro system kit, because it abbreviates log prefixes in weird ways (`DEBUG` => `DEBG`, `ERROR` => `ERRO`). This PR also adds a feature, `full_log_level_prefix`, which just has slog log the full prefix, which will allow devops to remove this custom patches.
=> feat: add new features to hiro-system-kit

Cargo.lock, components/clarinet-sdk-wasm/Cargo.toml
Patch release of clarinet-sdk-wasm to include the updated pox-4.clar contract (#1409)
The clarinet-sdk doesn't need to be updated for this one
=> chore: clarity-sdk-wasm v2.4.2

Cargo.lock, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/src/core.rs
Fix and release clarinet-sdk-wasm
This fix doesn't require a change on clarinet-sdk
=> fix: allow epoch 2.5 in clarinet-sdk

components/clarinet-sdk/vitest-helpers/src/clarityValuesMatchers.ts, components/clarinet-sdk/vitest-helpers/tests/clarityValueMatchers.test.ts
When using the sdk with vitest, if the custom matcher expects the wrong types, we keep error messages short
(eg: `expect(Cl.uint(1)).toBeOk(Cl.uint(1))` will throw `actual value must be a Clarity "UInt", received "ResponseOk"`)
This should be improved to display a more detailed error diff, but it requires some more work so that the error message remain readable, even when the test is handling big set of data (such as big lists or buffers).
This PR simply handle a quick fix for the common case were `expectOk` actually receive a ResponseError. We should display the received error
=> fix: improve error message in sdk custom matchers

.github/workflows/pkg-version-bump.yaml
The release actions failed on the homebrew step for clarinet 2.5.0:
https://github.com/hirosystems/clarinet/actions/runs/8690598712
With the error:
```
Invalid usage: clarinet: no `--url` or `--version` argument specified!
```
I was able [to open the homebrew PR](https://github.com/Homebrew/homebrew-core/pull/169081) by running this command locally:
```console
brew bump-formula-pr \
--no-browse \
--no-audit \
--force \
--tag 22e10c2f004ebdc3d07cd475844eaa4d11ebbb75 \
--version 2.5.0 \
clarinet
```
Looks like there was a breaking change in the bump-formula-pr command
=> ci: fix homebrew release

Cargo.lock, Cargo.toml
The `clarity-jupyter-kernel` component is unmaintained.
Maybe we could fully remove it, or keep it maintain it some day. In the meantime, it can safely be removed from the workspace.
It simplifies the cargo.lock file and remove some very old dependencies. Especially `failure` which trigger `Critical` [dependabot alerts on this repo](https://github.com/hirosystems/clarinet/security/dependabot).
Other than that, this PR has no impact.
=> chore: remove jupyter kernel from workspace

components/clarinet-deployments/src/requirements.rs, components/clarity-repl/src/repl/mod.rs
- Make 2.5 he default epoch 
- Set 2.5 block height: https://explorer.hiro.so/block/0x813e5b09c962905439fb21b5969e826b7a0f744f70ee80b2d7a8a00341d95f8c?chain=mainnet
=> chore: update 2.5 constants

.vscode/settings.json, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/deployment_plan_test.rs, components/clarity-lsp/src/common/requests/completion.rs, components/clarity-lsp/src/common/requests/definitions.rs, components/clarity-lsp/src/common/requests/document_symbols.rs, components/clarity-lsp/src/common/requests/signature_help.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, components/stacks-network/src/chains_coordinator.rs
Because of the way rust-analyzer was setup in .vscode/settings.json, clippy wasn't running on tests.
In the future, let's setup clippy in the CI as well, it shouldn't rely on the editor config
=> refactor: fix clippy warnings in tests

components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/types.rs, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/tests/deployment-plan.test.ts, components/clarinet-sdk/tests/simnet-usage.test.ts, components/clarity-repl/src/analysis/coverage_tests.rs, components/clarity-repl/src/repl/session.rs
Fix #1435
This PR started as a bug fix, but as I worked on it, I found that I could get massive perf improvements.
In the SDK `init_session`, some data is cached. Before this PR, just de deployment was cached.
But the **whole session** can actually be cached. It reduces file system access by a lot (in a Vitest context, we now only need to read the manifest and contract once) and reduce the time spent parsing contracts.
On my machine (M1), the cached `init_session` go from more than 100ms to a few ms (the time taken for `cache.clone()`). And knowing that `init_session` is called before each test, it takes the time to run tests in a project like pox-4 testing down from 32sec to 6secs
It also reworks a bit the session and the SDK structs
=> fix: improved sdk deployment plan handling and perf improvements

components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/src/index.ts, components/clarinet-sdk/tests/pox-locking.test.ts, components/clarinet-sdk/tests/reports.test.ts, components/clarinet-sdk/tests/simnet-usage.test.ts, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs
To be rebased on main and merged after #1437 
The sdk was always tracking costs and coverage reports even when it wasn't enabled.
By only enabling it when needed, we get better performance
=> fix: add options to enable or disable costs and coverage reports in sdk

Cargo.lock, components/clarity-repl/Cargo.toml, components/clarity-repl/src/frontend/terminal.rs, components/clarity-repl/src/repl/debug/cli.rs
- upgrade rustyline dependency
- fix `skip_next` behavior when parsing user input in clarinet console
Fix #1323
Fix #1271
Fix #616
=> Upgrade rustyline

Cargo.lock, components/clarity-events/src/analysis/mod.rs, components/clarity-events/src/bin.rs, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/interpreter.rs, components/stacks-codec/Cargo.toml, components/stacks-network/Cargo.toml, components/stacks-network/src/chains_coordinator.rs
The branch we use on stacks-core has been updated with the latest changes of `develop`.
A new branch `feat/clarity-wasm-develop` has been pushed https://github.com/stacks-network/stacks-core/pull/4756
=> chore: upgrade clarity vm

components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/tests/deployment-plan.test.ts, components/clarinet-sdk/tests/fixtures/Clarinet.toml, components/clarinet-sdk/tests/fixtures/contracts/block-height-tests.clar, components/clarinet-sdk/tests/reports.test.ts, components/clarinet-sdk/tests/simnet-usage.test.ts, components/clarity-lsp/src/common/requests/signature_help.rs, components/clarity-repl/Cargo.toml
In `sdk.mine_block`, `session.advance_chain_tip(1);` must be called before executing the contract calls.
This PR includes other minor fix
=> fix: block height increment in sdk mine_block

Cargo.lock, Cargo.toml, components/clarity-repl/src/repl/tracer.rs
Fix #1453 
This PR patches a potential panic when display the trace.*
The indentation is still wrong when showing the traces involving `contract-call?`
This implementation should be revisited in future work of the the traces (eg: when implemented traces in unit tests)
=> fix: prevent panic in trace

components/clarinet-sdk-wasm/src/core.rs, components/clarity-repl/src/repl/session.rs
This change was probably a good idea, in an effort to get simnet closet to real network. But it's also a breaking change with little to no benefit
=> fix: revert preventing epoch being set to lower epoch in simnet

components/stacks-network/src/chains_coordinator.rs
Slightly improve log following #1478
=> fix: print error if deployment start fails

components/clarity-repl/src/repl/datastore.rs
This condition was causing issue in the rust analyzer, that wouldn't correctly know if the trait was fully implemented or not
=> fix: better compiling condition on datastore get_side_store method

components/clarinet-cli/src/generate/project.rs
The testnet.toml file was created in the wrong directory
=> fix: testnet.toml path in project creation template

Cargo.lock, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/interpreter.rs
Get the latest version of clarity and clarity-wasm.
Also allowing to properly handle the `PEER_VERSION_EPOCH` in the datastore (the versions where previously not all properly exported from stacks-core)
=> chore: upgrade clarity-vm and clar2wasm

Cargo.lock, Cargo.toml, components/clarinet-cli/Cargo.toml, components/clarinet-deployments/Cargo.toml, components/clarity-repl/Cargo.toml, components/stacks-codec/Cargo.toml, components/stacks-network/Cargo.toml, components/stacks-network/src/ui/ui.rs, components/stacks-rpc-client/Cargo.toml
This PR update some dependencies, mainly
- tokio
- reqwest
- ratatui (really appreciated the [detailed breaking changes list](https://github.com/ratatui-org/ratatui/blob/main/BREAKING-CHANGES.md))
- clap
- ctrlc
And a lot of sub-dependencies.
It goes in pair with https://github.com/hirosystems/chainhook/pull/627 which should be merge first.
I'm doing some maintenance in our dependencies in an attempt to keep them updated and to optimize compile times. Trying to remove some older versions especially when we already import newer ones (we have a lot of dependencies with multiple versions imported).
This PR is a step in this direction. It's not a one-shot PR but instead an attempt to start having a better dependencies version management in our projects.
Before (main)
After (this branch)
=> chore: update reqwest and tokio version and other dependencies

Cargo.lock, components/clarinet-cli/Cargo.toml, components/clarinet-deployments/Cargo.toml, components/clarity-events/Cargo.toml, components/clarity-repl/Cargo.toml, components/hiro-system-kit/Cargo.toml, components/stacks-devnet-js/Cargo.toml, components/stacks-network/Cargo.toml
Remove unused dependencies.
- Lot's of dependencies in clarinet-cli/Cargo.toml are unused. This is likely caused by the fact that `clarinet-cli` was the original crate and was then split into many crates (about 2 years ago). But this Cargo.toml wasn't cleaned. 
- clarinet-utils was often imported but unused
This as a low impact on the cargo.lock and the workspace number of dependencies, since the dependencies removed from clarinet-cli are spread in other components. Still a nice clean of the clarinet-cli cargo.toml with about a third of the direct dependencies removed
I sued `cargo machete` to get an idea of the dependencies that could be removed. Along with carefully checking that whole still compiles. The CI will also ensure that for all targets
=> chore: remove unused dependencies

.github/workflows/ci-sdk.yaml, Cargo.lock, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/README.md, components/clarinet-sdk/README.md, components/clarinet-sdk/browser/package.json, components/clarinet-sdk/node/package.json, components/clarinet-sdk/node/src/vitest/index.ts, components/clarinet-sdk/node/tsconfig.cjs.json, package-lock.json, package.json
Superseding #1500
From @bradleyayers: 
> The location of node_modules is not guaranteed to be relative to the current directory (e.g. in workspaces). A better solution here is to update package.json exports to include the file.
This fixes it and also update some of the sdk dependencies.
The fix is available and can be tested with `npm i --force @hirosystems/clarinet-sdk@2.8.0-beta6`.
I also tested in an npm workspace setup (not tested with pnpm or yarn, @bradleyayers let me know if you can give it a try)
=> fix: improve vitest matcher sources resolver

components/clarinet-cli/src/deployments/mod.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/generate/changes.rs, components/clarinet-cli/src/generate/contract.rs, components/clarinet-cli/src/generate/project.rs, components/clarinet-files/src/network_manifest.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/analysis/coverage.rs, components/stacks-codec/src/codec.rs
=> fix: clippy warning v1.80

components/clarity-repl/src/repl/interpreter.rs
Since stacks-block-height and burn-block-height can be advanced independently in simnet (independently), the tenure-height should depend on burn block height
=> fix: tenure height depends on burn block height

components/clarinet-cli/src/generate/project.rs
The Devnet.toml config generated by default should auto_extend stacking orders by default.
Auto extending stacking orders allows to maintain epoch 3.0
=> feat: auto extend stacking_orders in devnet config by default

components/clarity-vscode/client/package.json, components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json
Bump Clarity VSCode version to 1.14.0.
Also upgrading some of the dev dependencies.
This version has already been manually released to OVSX and the VSCode marketplace
=> chore: release vscode extension

.github/workflows/ci-cli.yaml, .github/workflows/ci.yaml
Upgrade actions/upload-artifacts and actions/download-artifacts to v4.
https://github.com/hirosystems/clarinet/security/dependabot/211
=> ci: upgrade actions/upload-artifact and download-artifact to v4

components/clarinet-cli/src/deployments/types.rs
This PR addresses an issue with the conversion from micro STX (uSTX) to STX during deployment. Previously, the conversion was not handled correctly, leading to incorrect STX values being applied. This fix ensures that the conversion is accurate and that the correct STX values are used.
Related issues and PRs:
Issue: #1447
No breaking changes are introduced by this PR.
Example
Before this fix, deploying with micro STX values would result in incorrect STX values being applied. After this fix, the conversion is handled correctly, ensuring that the deployed values are accurate.
=> fix: convert correctly from uSTX to STX when applying a deployment on issue #1447

components/stacks-network/src/chains_coordinator.rs
Tihs is a patch for a case that should not happen under normal conditions.
More investigation to happen with block chain team.
Also, this only impacts the UI
=> feat: handle stacks reorg

components/clarinet-cli/src/generate/contract.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/node/tests/reports.test.ts, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/analysis/coverage.rs, components/clarity-repl/src/analysis/coverage_tests.rs, components/clarity-repl/src/analysis/mod.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, package-lock.json
Refactoring how we handle the code coverage hook in the session, in order to make it easier to pass more hooks to the contract-calls. Should be merged before #1574 
This also fixes some of the behavior in the PR: 
- function hit count
- report coverage for `simnet.runSnippet` and `snippet.execute`
There's still room for improvement, but I think this a ready to start adding more hooks in the sdk
=> refactor: better eval hooks handling in contract calls

components/clarinet-deployments/src/requirements.rs
These values has been outdated for a while now (4 months). When the primary testnet was restarted to use the bitcoin regtest.
And the epoch 3.0 switch is set to happen at block 56457 (today).
Check epoch values here: https://api.testnet.hiro.so/v2/pox
=> feat: update testnet epochs heights

components/stacks-codec/src/codec.rs
Type definitions were taken directly from stacks-core.
=> feat: add types to support `StacksSignerMessage` serialization

components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/requests/capabilities.rs
A client can send partial initialization options, e.g.:
```lua
require('clarinet') -- Adds clarinet LSP
lspconfig.clarinet.setup(extend_config({
cmd = {'/run/current-system/sw/bin/bash', '/tmp/wrapper.sh'},
init_options = {completion = true}
}))
```
When that happens, the deserialization from the following code would fail, because all other required fields of `InitializationOptions` would be missing.
https://github.com/hirosystems/clarinet/blob/90cb0158d532dd34d29fa9e396f6dc65cb26a89d/components/clarity-lsp/src/common/backend.rs#L372-L376
This PR fixes that. In addition, it removes the unnecessary (I think) cast to string as we are already dealing with a `serde_json::Value` instance.
No.
See above.
---
=> fix: LSP initialization options

components/clarinet-cli/src/lsp/native_bridge.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarity-lsp/src/common/backend.rs
Clippy fixes for [large_enum_variant](https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant)
In the LSP, the `Initialize` Response and Request are only sent at the initialization of the LSP, then it's only the other kinds that are used. So it really makes sense to box those.
I preferred to ignored the changes in deployments, because clarinet onchain deployments are less memory intensive (and, less used as well). So the benefits in changing those was less obvious
=> refactor: improve handling of enums with big size variations

CHANGELOG.md, Cargo.lock, Cargo.toml, components/clarinet-sdk/browser/package.json, components/clarinet-sdk/node/package.json, components/stacks-devnet-js/package.json, package-lock.json
Release 2.10.0.
This release is important to set the primary testnet epoch 3.0 height (used in requirements)
=> chore: release 2.10.0

Cargo.lock, components/clarity-repl/src/repl/datastore.rs, components/stacks-codec/Cargo.toml, components/stacks-codec/src/codec.rs
Mostly code pulled from stacks-core
This PR also cascades the changes following the removal of wsts and the clarity 3 changes with `get_stacks_height_for_tenure_height`
=> refactor: update codec

Cargo.lock, components/clarinet-cli/src/deployments/mod.rs, components/clarinet-cli/src/devnet/package.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/frontend/dap.rs, components/clarinet-cli/src/frontend/telemetry.rs, components/clarinet-deployments/Cargo.toml, components/clarinet-deployments/src/deployment_plan_test.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-deployments/src/types.rs, components/clarinet-files/Cargo.toml, components/clarinet-files/src/lib.rs, components/clarinet-files/src/network_manifest.rs, components/clarinet-sdk-wasm/src/core.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/mod.rs, components/stacks-devnet-js/src/lib.rs, components/stacks-network/Cargo.toml, components/stacks-network/src/chains_coordinator.rs, components/stacks-network/src/orchestrator.rs
- update some the dependencies (clap, ratatui, reqwest, serde)
- implement clarinet's own version of `StacksNetwork` and `BitcoinNetwork`, instead of importing it from `chainhook-types`. This allows to remove the chainhook dependency from `clarinet-files` and only have it in `stacks-network` (with `chainhook-sdk` and `chainhook-types` along each other). So that `clarinet-lsp` and `clarinet-sdk` don't rely on chainhook at all anymore 👍 
- i could have ported the `is_<network>` methods as well, but I don't think there's a big benieft if adding online helpers when we can just use the `matches!` macro
- with this, chainhook could even consider merging chainhook-sdk and chainhook-types in only one package
=> chore: update dependencies

components/clarinet-cli/src/frontend/dap.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-sdk-wasm/src/core.rs, components/clarity-events/src/bin.rs, components/clarity-repl/src/analysis/coverage_tests.rs, components/clarity-repl/src/repl/session.rs
wip - exploring an other interface for session hooks
With this approach:
- the Session is more aware of it's hooks
- instead of passing `eval_hooks` to every functions (`eval`, `deploy_contract` , `call_contract`), the caller only enable an hook once
- in the future we could have `session.enable_debug_print_hook`, `session.enable_tracer_hook`, etc
- I added `.eval_with_hooks` that keeps the same behaviour and is backward compatible with exisintg implementation. It allows to evaluated snippets with arbitrary hooks
- Should we choose to use the implemation, I should add some documentation in the comments for the `eval_with_hooks` method
Concerns: 
- is the Session supposed to be that aware of the hooks, or is it better to keep them as parameters, so that the Sessionis mor versatile
=> feat: session.eval_with_hooks

components/clarinet-deployments/src/requirements.rs
[Testnet block](https://explorer.hiro.so/block/0xdd4bca3f090161226fec5284b04fc47695ebf7ed694d439c8670f3c91ecf5a62?chain=testnet)
[Mainnet block](https://explorer.hiro.so/block/0xcff697c402c75056fbfec4386a568d9039458d8384b8a7312be391805d6ecd14?chain=mainnet)
The testnet height previously set was the burn block height instead of stacks block height
=> refactor: set epoch 3.0 block height

.github/workflows/ci-sdk.yaml, Cargo.lock, Cargo.toml, components/clarinet-files/Cargo.toml, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk-wasm/src/lib.rs, components/clarinet-sdk-wasm/src/test_wasm.rs, components/clarinet-sdk/clarinet-sdk.code-workspace, components/clarity-lsp/Cargo.toml
- set up wasm-bindgen
- add some simple tests
- run in CI
It kind of test the same thing as the existing clarinet-sdk wasm tests, more in a more "unit testing way" since it only test the wasm part. It also wayy faster to run. Both test strategies are useful
=> tests: setup basic wasm-bindgen tests for the sdk

README.md
Navigate a link to testnet page.
---
=> docs(README): recent link testnet

components/clarinet-deployments/src/requirements.rs
On the primary testnet, all of the boot contracts are deployed in #1, starting epoch 2.5. And epoch 3.0 starts just a few blocks later
=> fix: new testnet epoch heights

components/clarity-repl/src/repl/session.rs
The error has `bold` as format, but that wasn't expected on the assert. I've updated the assert.
=> fix unit test: update error expected format

components/clarinet-cli/examples/cbtc/README.md, components/clarinet-cli/examples/cbtc/serverless/handler.ts, components/clarinet-cli/src/generate/contract.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-repl/src/analysis/annotation.rs, components/stacks-codec/src/codec.rs
=> chore: fix some typos in comment

components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/frontend/dap.rs, components/clarinet-files/src/lib.rs, components/clarinet-files/src/project_manifest.rs, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/clarinet-sdk.code-workspace, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/remote_data.rs, components/clarity-repl/src/repl/settings.rs, components/clarity-vscode/web-extension.code-workspace, components/stacks-devnet-js/src/lib.rs, package-lock.json
The VSCode was partially broken due to #1503 
The root cause it due to bundling issue: the [JS snippet](https://github.com/hirosystems/clarinet/blob/59e015b497b4b5d67463633b962079aa41506880/components/clarity-repl/js/index.mjs) that is needed to make synchronous http calls in the clarity-repl could not be loaded in the VScode JS environment.
Hopefully, the LSP doesn't need this feature, so let's just disable it with a cargo feature flag
=> fix: vscode extension

.github/workflows/ci.yaml, Cargo.lock, components/clarinet-deployments/Cargo.toml, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-files/Cargo.toml, components/clarinet-files/src/lib.rs, components/clarinet-files/src/network_manifest.rs, components/clarinet-utils/Cargo.toml, components/clarinet-utils/src/lib.rs, components/stacks-devnet-js/Cargo.toml, components/stacks-devnet-js/src/lib.rs, components/stacks-rpc-client/Cargo.toml, components/stacks-rpc-client/src/crypto.rs, components/stacks-rpc-client/src/lib.rs, components/stacks-rpc-client/src/rpc_client.rs
Just some maintenance work.
- remove `tiny-hderive` - it's old and unmaintained and brought a lot of old version of [other dependencies](https://crates.io/crates/tiny-hderive/0.3.0/dependencies)
- also update reqwest
=> refactor: remove tiny hderive

components/clarinet-deployments/src/lib.rs
When automatically updating a deployments plan, if contracts where removed from a batch leaving it empty, we still keep the empty batch in the deployment plan
=> fix: avoid empty deployment batches

components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/session.rs, components/clarity-repl/tests/session_with_remote_data.rs
Preserve burn-block-height behavior in 3.x
https://github.com/stacks-network/stacks-core/pull/5524
=> fix: burn-block-height in at-block at epoch 3.x

.github/workflows/ci-sdk.yaml
Run clarinet-sdk tests in node 20 and 22
=> ci: run sdk tests in node 20 and 22

Cargo.lock, Cargo.toml, components/clarinet-cli/Cargo.toml, components/clarinet-deployments/src/diagnostic_digest.rs, components/clarinet-sdk-wasm/Cargo.toml, components/clarinet-sdk/node/tests/simnet-usage.test.ts, components/clarity-jupyter-kernel/src/jupyter/core.rs, components/clarity-repl/Cargo.toml, components/clarity-repl/src/repl/session.rs, components/hiro-system-kit/Cargo.toml, components/hiro-system-kit/src/macros.rs, components/stacks-network/Cargo.toml
We were using 2 crates to colorize text in terminal "colored" and "ansi_term"
- colored is maintained and automatically handle wasm build (by not colorizing text in non-terminal build, removing the need for atty)
- ansi is unmaintained
=> refactor: use colored

components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden.rs
Simply moves the golden tests to appropriate place for integrations, separating from unit tests
=> chore: move golden tests alongside relevant data

components/clarinet-cli/examples/billboard/package-lock.json, components/clarinet-cli/examples/billboard/package.json, components/clarinet-cli/examples/cbtc/deployments/default.simnet-plan.yaml, components/clarinet-cli/examples/cbtc/package-lock.json, components/clarinet-cli/examples/cbtc/package.json, components/clarinet-cli/examples/counter/package-lock.json, components/clarinet-cli/examples/counter/package.json, components/clarinet-cli/examples/simple-nft/package-lock.json, components/clarinet-cli/examples/simple-nft/package.json, components/clarinet-cli/examples/swappool/package.json, package-lock.json
In the examples:
- clarinet 2.14
- vitest 3.x
=> chore: update cli example npm dependencies

components/clarinet-cli/src/generate/project.rs
We can support vitest@3.x since vitest-environment-clarinet@2.3.0
https://github.com/hirosystems/vitest-environment-clarinet
Future projects should use it by default
=> chore: update project template npm dependencies

components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden-intended/BNS-V2.clar
- closes #1685 
- fix: un-nesting the trait args properly
New format
```lisp
(define-trait token-trait
(
(transfer? (principal principal uint) (response uint uint)) ;; comment
(get-balance (principal) (response uint uint))
)
)
```
Extra fixes included (from https://github.com/hirosystems/clarinet/discussions/1689#discussioncomment-12265035):
- fix un-stylized principal value
- remove some nasty old constant formatting and use the same generic code for all of them (define-nft/constant/ft etc...)
=> chore: fix define-trait format w/ test

components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden-intended/BNS-V2.clar
- fix the missing comment after top-levels
- fix documentation comments `;;;`
https://github.com/hirosystems/clarinet/discussions/1689#discussioncomment-12253506
=> chore: fix comment parsing and missing bugs

components/stacks-network/src/chains_coordinator.rs, components/stacks-rpc-client/src/mock_stacks_rpc.rs, components/stacks-rpc-client/src/rpc_client.rs
The previous logic was picking an arbitrary bitcoin block as an argument to pass to the mint call.
It was very likely that whatever this height was, it was skipped (because a lot of bitcoin blocks are skipped around epoch 3.0 switch).
The PR just takes the latest bitcoin block, instead of an arbitrary one
=> fix: make sbtc funding on devnet more robust

components/clarity-repl/src/repl/settings.rs
`skip_serializing_if` was used to avoid adding the remote data setting to every project manifest when we released it.
We should also have hnadled the deserialization if the field wasn't set, especially for devnet-api.
there are multiple way of handling it (we could also handl deserialisation if the field wasn't set), let's just keep it simple and remove skip_serializing
=> fix: serialize remote_data setting

Cargo.toml, components/clarinet-cli/Cargo.toml, components/clarinet-cli/src/lib.rs, components/clarinet-deployments/Cargo.toml, components/clarinet-deployments/src/lib.rs, components/clarinet-files/Cargo.toml, components/clarinet-files/src/lib.rs, components/clarinet-files/src/network_manifest.rs, components/clarinet-format/Cargo.toml, components/clarinet-sdk-wasm/Cargo.toml, components/clarity-events/Cargo.toml, components/clarity-lsp/Cargo.toml, components/clarity-lsp/src/common/requests/definitions.rs, components/clarity-lsp/src/lib.rs, components/clarity-lsp/src/utils/mod.rs, components/clarity-repl/Cargo.toml, components/clarity-repl/src/lib.rs, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/debug/mod.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/mod.rs, components/clarity-repl/src/repl/session.rs, components/clarity-vscode/web-extension.code-workspace, components/clarity-vscode/webpack.config.dev.js, components/clarity-vscode/webpack.config.js, components/stacks-network/Cargo.toml
Because it compiles to both native and wasm platform, clarinet uses conditional dependency management and compilation.
I could make dependency management mrpoe difficult than it should be
Instead of managing conditional dependencies with cargo feature, we can use cargo target dependencies instead.
So instead of this
```toml
[dependencies]
clap = { optional = true }
[features]
default = ["cli"]
cli = ["clap"]
wasm  = []
##########
#package-b
[dependencies]
package-a = { path = "../package-a", optional = true }
[features]
default = ["cli"]
cli = ["package-a/cli"]
wasm  = ["package-a/cli"]
```
We now do this
```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { optional = true }
##########
#package-b
[dependencies]
package-a = { path = "../package-a" }
```
With this …
=> refactor: rework wasm conditional compilation

components/clarinet-files/src/network_manifest.rs, components/stacks-network/src/chains_coordinator.rs
Because the sbtc contract can be deployed at the end of a deployment plan, is possible that the `boot_completed` is set to true while the sbtc contracts are still in the mempool. So when they are deployed (after boot is completed), the sbtc funding tx were not triggered.
This PR fixes it.
it also tweaks some devnet timing value, that are promising to get a faster and stable devnet start to epoch 3.0
=> fix: improve devnet sbtc handling

components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/frontend/dap.rs, components/clarinet-cli/src/generate/project.rs, components/clarinet-cli/src/lsp/native_bridge.rs, components/clarinet-deployments/src/diagnostic_digest.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-files/src/project_manifest.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/requests/completion.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/repl/debug/dap/mod.rs, components/clarity-repl/src/repl/diagnostic.rs, components/clarity-repl/src/repl/session.rs, components/stacks-network/src/lib.rs, components/stacks-network/src/orchestrator.rs, components/stacks-network/src/ui/ui.rs, components/stacks-rpc-client/src/crypto.rs
I've been doing some code cleanup on stacks-core, so I thought I'd try it on this repo also. This repo is already configured to use Clippy, which is great, but by default Clippy does not apply it's "nursery" (experimental) lints. Some of these can be useful and are worth applying. Specifically, I checked the following:
```
clear_with_drain
collection_is_never_read
needless_collect
iter_with_drain
mutex_integer
set_contains_or_insert
trivial_regex
useless_let_if_seq
unused_rounding
unnecessary_struct_initialization
tuple_array_conversions
```
Only `redundant_clone` and `clear_with_drain` resulted in any changes
No
This can make the code more clear and improve performance by removing unnecessary function calls. For example, one change I made was:
```rust
fn level_to_string(level: &Level) -> …
```
=> chore: Apply Clippy lints  `redundant_clone` and  `clear_with_drain`

components/clarinet-cli/src/frontend/cli.rs, components/clarinet-format/README.md
Adds basic readme to formatter with a couple cli examples and vscode screenshot
=> chore: add formatter readme

Cargo.lock
update some well maintain heavily used crates in clarinet
`tokio clap ctrlc divan libsecp256k1 reqwest`
This PR addresses a [recent vulnerability (low) in tokio](https://github.com/hirosystems/clarinet/security/dependabot/312)
=> chore: update cargo dependencies

components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/remote_data/mod.rs, components/clarity-repl/tests/session_with_remote_data.rs
In the context of mainnet-execution simulation, fixes:
- `(get-tenure-info? vrf-seed <height>)` - `vrf-seed` is fetched in `/v3/sortitions/burn_height/<burn-height>`
- `(get-tenure-info? time <height>)` - `burn_block_time` was already fetched in `/extended/v2/blocks/<height>`
=> fix: mxs tenure info

components/clarity-lsp/src/common/backend.rs, components/clarity-vscode/client/package.json, components/clarity-vscode/client/src/common.ts, components/clarity-vscode/client/src/customVFS.ts, components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json, components/clarity-vscode/server/src/common.ts
A few things in this PR:
- update vscode extension npm dependencies
- remove the manual request to lsp server to format document, the lsp does it on its own
- fix the lsp option "format" to "formatting", aligned with the [initialization options](https://github.com/hirosystems/clarinet/blob/ce6bf85ca18d48940210a9c4449a48c69a4b5c53/components/clarity-lsp/src/common/requests/capabilities.rs#L15)
- there was a bug were the "initialization options" were not correctly parsed and would silently failed. This PR fixes it
=> fix: lsp formatting option

.github/workflows/pkg-version-bump.yaml
Uses a GitHub App generated token for Homebrew releases
=> ci: update release to use GH App token

components/clarinet-sdk/browser/src/defaultVfs.ts, components/clarinet-sdk/browser/src/index.ts
In the browser version of the clarinet-sdk, use `globalThis` instead of window, so that it also works in web workers.
=> fix: set fsStore in globalThis

components/clarinet-sdk/node/tests/deployment-plan.test.ts, components/clarinet-sdk/node/tests/fixtures/EmptyManifest.toml, components/clarinet-sdk/node/tests/pox-locking.test.ts, components/clarinet-sdk/node/tests/simnet-usage.test.ts, components/clarinet-sdk/node/tests/support-clarity-version.test.ts, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/session.rs
To get simnet behavior closer to what happens in mainnet, and prevent weird behaviour (when decreasing epoch):
- the epoch in simet can not be decreased
- updating the epoch increments the burn block height
fix: #1669
Both changes can lead to breaking changes in simnet and can require tests to be updated
=> feat: improve simnet epoch handling

components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden-intended/BNS-V2.clar, components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar, components/clarinet-format/tests/golden-intended/comments.clar, components/clarinet-format/tests/golden/comments.clar
Preserves user-provided newlines but squashes 2 or more into 1
closes #1697
=> fix: preserve user newlines 

prepare-release.sh
- vscode version is now the same as clarinet overall, so no need to prompt
- update clarinet-sdk deps
=> chore: simplify prepare-release and remove vscode special casing

components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden-intended/BNS-V2.clar, components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
- closes #1799 
This fixes the breakage in citycoins protocol contracts
=> fix: list formatting breakage

components/clarinet-cli/examples/billboard/package.json, components/clarinet-cli/examples/cbtc/package.json, components/clarinet-cli/examples/counter/package.json, components/clarinet-cli/examples/package-lock.json, components/clarinet-cli/examples/simple-nft/package.json, components/clarinet-cli/examples/swappool/package.json, components/clarinet-cli/src/generate/project.rs
`typescript` and `vite` are not needed since vitest 2.x
`@types/node` is required so that ts knows we are running in a node env
Note:
This changes only apply to new project, older project don't necessarily need to adapt, but we recently released the ["anatomy of a clarinet project" documentation](https://docs.hiro.so/stacks/clarinet/guides/anatomy-of-a-clarinet-project) to help developers maintain there project and dealing we recent versions of node and clarinet
=> fix: update npm project template

components/clarinet-cli/src/frontend/cli.rs
Fixes #1816
This is needed to use the formatter with Helix editor (at least until LSP working). May also be useful with other text editors
Also, some refactoring in here so that all files aren't read into RAM at the same time
```sh
echo '(define-public (hello-world (input int)) (begin (print (+ 2 input)) (ok input)))' | clarinet format --stdin
```
```clarity
(define-public (hello-world (input int))
(begin
(print (+ 2 input))
(ok input)
)
)
```
---
=> feat: Add `--stdin` flag to formatter

components/clarity-lsp/src/common/requests/capabilities.rs
By default, all the LSP initialization options are initialized to `false`, which means that we have to add extra config to the editor to get anything working
This is because the struct `InitializationOptions` is using the `default()` generated by `#[derive(Default)]` rather than the one we wrote. This PR removes the derived `default()` 
No
We will no longer need this extra JSON to editor configs:
```json
"lsp": {
"clarity-lsp": {
"enable_lsp_tasks": true,
"initialization_options": {
"completion": true,
"completion_smart_parenthesis_wrap": true,
"completion_include_native_placeholders": true,
"document_symbols": false,
"formatting": true,
"go_to_definition": true,
"hover": true,
"signature_help": true
}
}
},
```
=> fix: Use correct `default()` function for initializing LSP options

components/clarinet-format/src/formatter/mod.rs
As part of the TS to Clarity transpiler project, I need to be able to format a Clarity AST (with no source) 
This PR makes the source optional in the formatter, and adds a `format_ast` function along with `format_file`
=> feat: accept ast only in the formatter

components/clarinet-cli/src/deployments/mod.rs, components/clarinet-cli/src/frontend/cli.rs, components/clarinet-cli/src/lsp/mod.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/src/onchain/mod.rs, components/clarinet-deployments/src/types.rs, components/clarinet-files/src/project_manifest.rs, components/clarity-lsp/src/common/backend.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/analysis/ast_dependency_detector.rs, components/clarity-repl/src/repl/debug/cli.rs, components/clarity-repl/src/repl/debug/dap/mod.rs, components/clarity-repl/src/repl/debug/mod.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, components/clarity-repl/src/repl/tracer.rs, components/stacks-codec/src/codec.rs, components/stacks-devnet-js/src/lib.rs, components/stacks-network/src/chainhooks.rs, components/stacks-network/src/chains_coordinator.rs, components/stacks-network/src/orchestrator.rs
Apply Clippy lint `manual_let_else`, which finds `match` statements that can be simplified to `let`/`else` statements. This change results in almost 200 fewer LOC in the repository
No
For example, this code:
```rust
let docker = match &self.docker_client {
Some(ref docker) => docker,
_ => return Err("unable to get Docker client".into()),
};
```
Simplifies to:
```rust
let Some(docker) = &self.docker_client else {
return Err("unable to get Docker client".into());
};
```
=> chore: Apply `clippy::manual_let_else`

components/clarinet-files/src/network_manifest.rs
Related to
- Clarinet issue: #1846 
- Explorer issue: https://github.com/hirosystems/explorer/issues/2312
As a quick fix, Clarinet devnet will use the old Explorer until it can use the new one.
=> fix: use old explorer in devnet

components/clarity-repl/src/repl/remote_data/http_request/native.rs, components/clarity-repl/src/repl/remote_data/mod.rs
MXS fetches Hiro API to retrieve mainnet/testnet data.
We sometimes hit the 40 requests per second rate limit.
This is especially true when running MXS integration tests against api.testnet.hiro.so, causing tests to be flaky?
This PR implements a retry mechanism for the native mxs http client.
It doesn't do it for the node and web browser client because hitting the limit in these env is less likely. And it's also less straightforward to implement (we can't just "sleep" in the browser or node)
=> feat: add rate limit in native mxs data fetching

.github/workflows/ci.yaml
Add target `x86_64-unknown-linux-musl` for Clarinet release build. Having a static binary will simplify Linux packaging
=> feat: Add release build for `x86_64-unknown-linux-musl`

components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/repl/debug/mod.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs
Apply `clippy::iter_with_drain`, which finds calls to `.drain(..)` which can be replaced by `into_iter()`. `into_iter()` is more efficient because it doesn't have to clear the collection being iterated over, and allows reuse of allocated memory
No
This code:
```rust
for (account, token, value) in accounts_to_credit.drain(..) {
self.credit_token(account, token, value);
}
```
Can be simplified to (note that `into_iter()` is implicit):
```rust
for (account, token, value) in accounts_to_credit {
self.credit_token(account, token, value);
}
```
=> chore: Apply `clippy::iter_with_drain`

components/clarity-lsp/src/common/state.rs
Currently goto definition for `contract-call?` is broken. It takes you to the correct line/column, but always in the current file, not where it is actually defined. I broke this in #1859 due to copy/pasting the first instance of `uri: contract_location.try_into().ok()?`. The following ones should use a different variable (`definition_contract_location`)
=> fix: Incorrect contract path in "Go to definition" reply from copy/paste error

components/clarity-lsp/src/common/requests/definitions.rs, components/clarity-lsp/src/common/requests/helpers.rs, components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/analysis/ast_visitor.rs, components/stacks-network/src/chainhooks.rs
Fixes: #785
Clicking "Go to Definition" on `impl-trait` and `use-trait` names should go to the corresponding `define-trait` declaration
No
=> feat: Go to trait definition for `impl-trait` and `use-trait`

components/clarity-lsp/src/common/state.rs, components/clarity-repl/src/repl/clarity_values.rs
This PR removes a clone (via `.to_owned()`) of the entire definitions hashmap that occurs on every definitions lookup. It should make the "Go to definitions" response a bit quicker
=> perf: Remove clone of definitions hashmap

components/clarinet-sdk/node/tests/remote-data.test.ts, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs
- fixes #1708 
Specify if contract calls are to non-existent methods or contracts
=> fix: better error messages for contract call failures

Cargo.lock, components/clarinet-format/Cargo.toml, components/clarinet-format/src/formatter/mod.rs, components/clarinet-format/tests/golden-intended/preserve_newlines.clar, components/clarinet-format/tests/golden.rs, components/clarinet-format/tests/golden/preserve_newlines.clar
=> Fix: preserve inner expr newlines (#1790)

components/stacks-network/src/orchestrator.rs
The devnet ports bindings wasn't work with docker 28.2.2 (docker dekstop 4.42.0) and above (tested in 28.3.0 / 4.43.0 as well).
This PR fixes it. Only tested in Docker v28.3.0
=> fix: devnet port binding

components/clarinet-cli/src/frontend/cli.rs, components/clarinet-deployments/src/lib.rs, components/clarinet-deployments/tests/deployment_plan.rs, components/clarinet-deployments/tests/genesis_accounts_funding.rs, components/clarinet-files/src/devnet_diff.rs, components/clarinet-files/src/network_manifest.rs, components/clarinet-files/src/project_manifest.rs, components/clarinet-format/src/formatter/mod.rs, components/clarity-events/src/analysis/mod.rs, components/clarity-repl/benches/simnet.rs, components/clarity-repl/src/analysis/coverage_tests.rs, components/clarity-repl/src/repl/datastore.rs, components/clarity-repl/src/repl/interpreter.rs, components/clarity-repl/src/repl/session.rs, components/clarity-repl/src/test_fixtures/clarity_contract.rs, components/stacks-rpc-client/src/mock_stacks_rpc.rs
Apply `clippy::redundant_clone`, which removes several unnecesary `.clone()` and `.to_string()` calls
=> perf: Apply `clippy::redundant_clone`

.github/workflows/ci-sdk.yaml, .github/workflows/release-sdk.yaml, components/clarinet-cli/examples/billboard/package.json, components/clarinet-cli/examples/billboard/tsconfig.json, components/clarinet-cli/examples/cbtc/package.json, components/clarinet-cli/examples/cbtc/tests/cbtc-token.test.ts, components/clarinet-cli/examples/cbtc/tsconfig.json, components/clarinet-cli/examples/counter/package.json, components/clarinet-cli/examples/counter/tsconfig.json, components/clarinet-cli/examples/package-lock.json, components/clarinet-cli/examples/simple-nft/package.json, components/clarinet-cli/examples/simple-nft/tsconfig.json, components/clarinet-cli/examples/swappool/package.json, components/clarinet-cli/examples/swappool/tsconfig.json, components/clarinet-cli/src/generate/project.rs, components/clarity-vscode/package-lock.json, components/clarity-vscode/package.json, package-lock.json, package.json
Maintenance PR
- chore: upgrade sdk npm dependencies
- chore: upgrade clarity-vscode npm dependencies
- chore: update and refresh `clarinet-cli/examples` dependencies and configs
- ci: build sdk with node 24.x
- ci: test sdk with ndoe 20.x and 24.x (skipping 22.x, no need to overkill the CI runs)
superseed #1916
=> chore: upgrade npm dependencies

.github/workflows/ci.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore: update the deprecated `set-output` run commands

components/clarity-repl/src/repl/session.rs
Without this change, Clarinet prints:
```
→ .ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.contract-2 contract successfully stored. Use (contract-call? ...) for invoking the public functions:
```
Now the `.` at the beginning is removed and the public and read-only functions are listed.
=> Fix: contract name printed in console

components/clarinet-cli/src/generate/project.rs
The only line that really matters here is: `@types/node": "^24.4.0",`
The node types are used to tell ts that node interfaces (such as `console.log`) are available globally
=> chore: update new project package.json

components/clarinet-sdk-wasm/src/core.rs, components/clarinet-sdk/node/vitest-helpers/src/vitest.setup.ts, components/clarity-repl/src/repl/session.rs
In #1974, I introduced improvement in the stack trace hook and better support for it in the SDK.
It shows the traces with a better error message whenever a contract-call fails (when there's an error in the vm)
This takes it a step further, and allows the test runner to show the stacks trace whenever a test fails.
=> feat: show stacks trace on test fail

components/stacks-network/src/chains_coordinator.rs
=> fix: publish stacking orders regardless of snapshot
