hirosystems/clarinet

README.md

Added more content to the README file

chore: updated README.md with more information

---

Cargo.lock
Cargo.toml
src/console/mod.rs
src/frontend/cli.rs
src/generators/changes.rs
src/generators/contract.rs
src/generators/mod.rs
src/generators/notebook.rs
src/test/deno.rs
src/test/mod.rs
vendor/deno/cli/tools/test_runner.rs

Address https://github.com/hirosystems/clarinet/issues/53

More flexibility for manifest-path handling

---

examples/counter/tests/counter_test.ts
src/test/deno.rs

Address https://github.com/hirosystems/clarinet/issues/45

fix: implement tx.transferSTX

---

README.md

This PR updates the README to provide installation instructions for the pre-built binary releases.

docs: add info on installing from pre-built binaries

---

.github/workflows/ci.yaml
.github/workflows/open-develop-pr.yml
.github/workflows/pkg-version-bump.yaml
README.md

* Adds a new workflow to auto-create a PR which bumps the clarinet version (untested)
* Updated formatting in workflows
* Updates brew documentation in README
Closes https://github.com/hirosystems/clarinet/issues/73

ci: add package manager workflow

---

.github/workflows/pkg-version-bump.yaml

* Fixes Homebrew automatic submission by adding missing env var needed for Github authentication
* Adds winget automatic submission - [tested here](https://github.com/microsoft/winget-pkgs/pull/21914)
Closes https://github.com/hirosystems/clarinet/issues/83

ci: post release workflows

---

.github/workflows/ci.yaml
.github/workflows/open-develop-pr.yml
.github/workflows/pkg-version-bump.yaml
.github/workflows/rustdoc.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
Dockerfile
README.md
src/integrate/events_observer.rs
src/integrate/orchestrator.rs
src/main.rs
src/types/chain_config.rs
xtask/src/dist.rs

This PR is upgrading to a version of Rocket (currently in RC) that does not require rust nightly, to address https://github.com/hirosystems/clarinet/issues/97 and fix distribution via brew.
It's also fixing some compatibility issues with Linux, raised in https://github.com/hirosystems/clarinet/issues/94.

Devnet adjustments

---

src/runnner/deno.rs
src/types/project_manifest.rs

Address https://github.com/hirosystems/clarinet/issues/173

chore: update default costs

---

src/frontend/cli.rs

The previous commit sent errors for unknown commands to the telemetry,
but did not show them on the screen. This fixes that issue and also
ensures that only unknown commands are reported to telemetry (not help
or version commands).

fix: show errors when parsing opts

---

src/lsp/clarity_language_backend.rs

Tested with PR https://github.com/hirosystems/clarity-lsp/pull/54

LSP adjustments

---

Cargo.lock
Cargo.toml
src/generate/project.rs

+ enable `check_checker` by default for new projects.

Update clarity-repl v0.20.0

---

src/integrate/ui/ui.rs

Fix for the issue #202.
And also improving the codebase removing some needless code.

issue with chunked information in Mempool section

---

src/runnner/deno.rs

fix: generate proper strings from contract results

---

Cargo.lock
Cargo.toml
src/frontend/cli.rs
src/generate/project.rs
src/lsp/clarity_language_backend.rs
src/poke/mod.rs
src/runnner/deno.rs
src/types/project_manifest.rs

This corresponds to changes in hirosystems/clarity-repl#85.

feat: update to work with new parser

---

.github/workflows/ci.yaml
node-bindings/package.json

Closes https://github.com/hirosystems/clarinet/issues/210

MacOS arm64 / Apple Silicon support

---

.github/workflows/ci.yaml
examples/counter/tests/counter_test.ts
src/generate/project.rs

Address https://github.com/hirosystems/clarinet/issues/297, by installing grcov on top of a stable toolchain, then switch to nightly toolchain for producing the coverage informations. Add 13s to the workflow on a non critical path, which sounds reasonable.

fix: repair test CI workflow

---

Cargo.lock
Cargo.toml
README.md
src/frontend/cli.rs
src/frontend/telemetry.rs
src/lsp/clarity_language_backend.rs
src/runnner/deno.rs

Dependent on https://github.com/hirosystems/clarity-repl/pull/116

Add support for debugger

---

src/frontend/cli.rs

I don't yet have a Windows test environment setup. I'm working on setting one up. If anyone would like to test this out on Windows, and let me know if it solves the problem, please comment here.

fix: Fix issue with telemetry prompt on windows

---

src/lsp/clarity_language_backend.rs

This adds the new contract ordering logic to the lsp, which fixes a bug exposed by the previous changes.

fix: fixed problem with contract ordering in lsp

---

src/frontend/cli.rs

*Continuation of #367, reworked (as per @obycode in https://github.com/hirosystems/clarinet/pull/367#issuecomment-1135035971) in order to take #333 into account.*
I assume that if the manifest path is empty, warn the user, skip deployments and artifacts, and just start an empty console session.
Output from `clarinet console`:

feat: allow empty console

---

components/clarity-repl/src/repl/session.rs
deno/index.ts

Fix 2 errors in the testing framework

---

README.md

Hi,
Was refining a bit the docs about the interacting with contract deployed on Mainnet. 
Mainly elaborating with a short example but also changing the syntax of adding requirements. 
Best,

Docs ### Interacting with contracts deployed on Mainnet

---

.github/workflows/ci.yaml
Cargo.lock
components/clarinet-cli/Cargo.toml

Fix CI errors

---

components/clarity-lsp/src/vscode_bridge.rs

The diagnostic notifications (ie: `Warning detected in following contracts: <...> `) were left ignored in #434.
This PR fixes it.
It also brings some improvements (better error handling, consistently use `JsValue::NULL` instead of `::null()`)

feat: vscode - send diagnostic notifications

---

Cargo.lock
components/clarinet-deployments/src/lib.rs
components/clarinet-deployments/src/requirements.rs
components/clarinet-files/Cargo.toml
components/clarinet-files/src/lib.rs
components/clarinet-files/src/network_manifest.rs
components/clarinet-files/src/project_manifest.rs
components/clarinet-files/src/wasm_fs_accessor.rs
components/clarity-lsp/Cargo.toml
components/clarity-lsp/src/common/backend.rs
components/clarity-lsp/src/vscode_bridge.rs

Along with other improvements in the code

feat: lsp improvements

---

components/clarity-vscode/server/src/common.ts

fix: completion item kind mapping

---

Cargo.lock
components/clarinet-cli/src/deployments/mod.rs
components/clarinet-cli/src/runner/api_v1.rs
components/clarinet-cli/src/runner/mod.rs
components/clarinet-deployments/Cargo.toml
components/clarinet-deployments/src/lib.rs
components/clarity-lsp/src/common/state.rs
components/clarity-vscode/client/src/clientBrowser.ts
components/clarity-vscode/package.json

refacto: performance optimisation with parser v2

---

components/clarinet-deployments/Cargo.toml

`reqwest` was not found when building for wasm. Not sure why this regression appeared.
Auto formatted the file

fix: wasm build

---

components/clarity-vscode/client/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
package-lock.json

Not much to review here. Can be safely merged.
Microsoft recommends to keep vsce always up to date so I applied all minor upgrades

VSCode: version bump and upgrade dependencies

---

.github/workflows/ci.yaml

Related to https://github.com/hirosystems/devops/issues/1042

Disable persistent creds on Docker image

---

README.md

Updated Clarinet README file with polish and some suggestions
Fixes https://github.com/hirosystems/clarinet/issues/478

updated Clarinet README file

---

components/clarinet-cli/src/frontend/cli.rs
components/clarinet-deployments/src/lib.rs

Address https://github.com/hirosystems/clarinet/issues/658

Fix: requirements calling boot contracts

---

components/clarinet-cli/src/frontend/cli.rs

Updated cli.rs file to point to the correct docs location for Clarinet testing.

Cli.rs file: updated links to point to the right docs location

---

components/clarity-vscode/package-lock.json

Minor versions upgrade of the vscode extension npm dependencies.
Microsoft recommences to keep vsce up to date before releasing

chore: upgrade extension dependencies

---

Cargo.lock
components/clarinet-cli/src/lsp/native_bridge.rs
components/clarity-lsp/Cargo.toml
components/clarity-lsp/src/common/backend.rs
components/clarity-lsp/src/common/hover_data.rs
components/clarity-lsp/src/common/mod.rs
components/clarity-lsp/src/common/state.rs
components/clarity-lsp/src/vscode_bridge.rs

feat: lsp - display documentation on hover

---

components/clarinet-files/src/project_manifest.rs

Having the wrong data type for clarity version or epoch would fallback to default instead of throwing an error.
example
```toml
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = "2" # should be integer
epoch = 3 # should be float
```
Would silently default to clarity 1 (default) and epoch 2.0 (default)
`epoch` is now expecting a float and wrong format will return errors

fix: clarity version and epoch parsing in manifest

---

components/clarinet-cli/src/frontend/cli.rs
components/clarity-repl/src/bin.rs
components/clarity-repl/src/frontend/terminal.rs
components/clarity-repl/src/repl/session.rs

fix: re-implement `::reload` command in REPL

---

components/clarity-repl/src/lib.rs
components/clarity-repl/src/repl/session.rs

Regression caused by handle_command signature change in #677

fix: repl was build issue

---

components/clarinet-deno/index.ts
components/clarinet-deno/types.ts

Adds `expectSTXBurnEvent(amount, sender)`

feat: add matcher for stx burn events

---

components/clarity-vscode/syntaxes/clarity.tmLanguage.json

Add all keywords from SIP-015 and SIP-020

Feat: add clarity 2 keywords to language syntax

---

components/clarinet-cli/src/generate/project.rs

Added the new configuration options needed for 2.1 / Clarity2 into the
generated Devnet.toml file.
Fixes: #715

feat: add commented out config for 2.1

---

components/clarity-repl/src/repl/session.rs

Pull Request to fix an issue with the PR #739 .
It wasn't being considered the case where the project has more than one asset to be displayed.
**Before the fix on this PR:**
**After the fix on this PR:**
If any other place needs attention, please let me know. Thanks!

fix: handle STX assets title

---

Cargo.lock
components/clarity-lsp/src/common/requests/completion.rs
components/clarity-repl/Cargo.toml
components/clarity-repl/src/analysis/ast_dependency_detector.rs
components/clarity-repl/src/analysis/check_checker/mod.rs
components/clarity-repl/src/repl/interpreter.rs

Now pulling the latest clarity vm from https://github.com/stacks-network/stacks-blockchain/pull/3478

feat: update clarity vm

---

components/clarinet-files/src/lib.rs
components/clarity-lsp/src/vscode_bridge.rs

I'll probably want to have a more scalable warning/error handling in the future but that's a start

Feat: warning when opened contract is not in manifest

---

docs/how-to-guides/how-to-set-up-local-development-environment.md

- Updated file: docs/how-to-guides/how-to-set-up-local-development-environment.md

Docs: Updated docs to set Clarity version of contract

---

docs/how-to-guides/how-to-use-deployment-plans.md
docs/troubleshooting.md

Fixed the html tags which were failing due to incomplete or unescaped html tags

880 close html like tags

---

.github/workflows/ci.yaml

Removed 2 fixed vulnerabilities, added one new

chore: update cargo audit whitelist

---

docs/how-to-guides/how-to-use-deployment-plans.md

I added video link to the deployment plans.

Added link to the youtube video

---

docs/feature-guides/analyze-with-check-checker.md
docs/feature-guides/chainhooks.md
docs/feature-guides/clarinet-deploy.md
docs/feature-guides/clarinet-integrate.md
docs/feature-guides/extend-clarinet.md
docs/getting-started.md
docs/how-to-guides/how-to-add-contract.md
docs/how-to-guides/how-to-check-contract.md
docs/how-to-guides/how-to-create-new-project.md
docs/how-to-guides/how-to-debug-contract.md
docs/how-to-guides/how-to-deploy-contracts.md
docs/how-to-guides/how-to-deploy-with-subnets.md
docs/how-to-guides/how-to-run-integration-environment.md
docs/how-to-guides/how-to-set-up-local-development-environment.md
docs/how-to-guides/how-to-test-contract.md
docs/how-to-guides/how-to-use-deployment-plans.md
docs/introduction.md
docs/troubleshooting.md

Re-opened instead of #888 to fix conflicts

docs: add topics

---

docs/feature-guides/analyze-with-check-checker.md
docs/feature-guides/chainhooks.md
docs/feature-guides/clarinet-deploy.md
docs/feature-guides/clarinet-integrate.md
docs/feature-guides/extend-clarinet.md
docs/getting-started.md
docs/how-to-guides/how-to-add-contract.md
docs/how-to-guides/how-to-check-contract.md
docs/how-to-guides/how-to-create-new-project.md
docs/how-to-guides/how-to-debug-contract.md
docs/how-to-guides/how-to-deploy-contracts.md
docs/how-to-guides/how-to-deploy-with-subnets.md
docs/how-to-guides/how-to-run-integration-environment.md
docs/how-to-guides/how-to-set-up-local-development-environment.md
docs/how-to-guides/how-to-test-contract.md

Added topics to all the articles to give deeper insights into the article.

Clarinet docs: Add topics

---

docs/how-to-guides/how-to-use-deployment-plans.md

Added links to all the topics in the deployment plans guide.

Added links to all the topics in the deployment plans how-to guide

---

README.md
docs/how-to-guides/how-to-test-contract.md

Explorer has been moved to hiro.so

docs: update explorer links

---

README.md

docs: format vscode's `launch.json` as JSON5

---

docs/how-to-guides/how-to-set-up-local-development-environment.md

docs: cross-link test contract how to guide

---

components/clarinet-cli/src/frontend/cli.rs
components/clarinet-cli/src/runner/deno.rs
components/clarinet-cli/src/runner/mod.rs
components/clarity-repl/src/analysis/coverage.rs

feat: allow specifying filename with test coverage

---

components/clarity-repl/src/repl/datastore.rs

This PR fixes #957 by setting the genesis block's `burn_block_time` field to the system's current time, in seconds.
It also updates the calculation on any given block to be in reference to the genesis block's time.

feat: use realistic block times

---

components/clarinet-files/src/network_manifest.rs
components/stacks-devnet-js/lib/index.ts
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/src/lib.rs
components/stacks-network/src/orchestrator.rs

Enable epoch 2.2 for pox-2 fix testing.

Enable Epoch2.2

---

components/clarinet-files/src/lib.rs
components/clarinet-files/src/network_manifest.rs
components/stacks-network/src/orchestrator.rs

Use the latest subnet image (`0.5.0`), subnet API image (`7.1.0-subnets.1`), and subnet contract `subnet-v1-2`.

chore: update subnet images and contract

---

Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-utils/Cargo.toml
components/clarity-events/Cargo.toml
components/clarity-repl/Cargo.toml
components/hiro-system-kit/Cargo.toml
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

While doing some maintenance checks on the repo, I found a few unused deps, but really not a lot. I removed it to help a little with the dependencies management

chore: remove unused deps

---

components/clarinet-files/src/network_manifest.rs

Also update subnet API to use the latest image, which is now subnet-compatible.
No
This just changes default values in Devnet.toml.
---

chore: update subnet node to 0.8.1

---

docs/how-to-guides/how-to-add-contract.md

- Added clarinet version and epoch configuration to the Clarinet.toml file.

Added epoch config to the clarinet toml file

---

components/clarinet-cli/examples/swappool/.gitignore
components/clarinet-cli/examples/swappool/Clarinet.toml
components/clarinet-cli/examples/swappool/README.md
components/clarinet-cli/examples/swappool/contracts/empty.clar
components/clarinet-cli/examples/swappool/settings/Devnet.toml
components/clarinet-cli/examples/swappool/tests/empty_test.ts
components/clarinet-deployments/src/lib.rs

Fix: #1079 
Follow up of https://github.com/hirosystems/clarinet/pull/997
With the previous fix, the order of the requirements would matter, now we get the right clarity version for each requirement
Note: I didn't add unit tests for project with nested dependencies. But I added the Alex project (which also revealed the bug prior to 997) to the release playbook.
I think this PR makes this part of code slightly simpler but I still think it can be revamped to be simpler and more robust

fix: clarity version of nested requirements

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml

chore: bump clarinet version to 1.7.1

---

components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json

I didn't actually bum the version in #1093...

chore: bump vscode enxtension to 1.7.1

---

docs/feature-guides/extend-clarinet.md

Edit typos and language fixes in the 'Extend Clarinet' doc
No

Edit typos and language fixes in the 'Extend Clarinet' doc

---

docs/feature-guides/chainhooks.md

- Added Chainhook documentation links to the references.

Added chainhook docs to references links

---

docs/introduction.md

https://github.com/hirosystems/docs/issues/424
---

Deleted the Image and added the new youtube playlist link

---

docs/feature-guides/clarinet-integrate.md

Edit typos and language fixes in the 'Clarinet Integrate' doc
No

Edit typos and language fixes in the 'Clarinet Integrate' doc

---

components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/src-ts/index.ts
components/clarinet-sdk/src/core.rs
components/clarinet-sdk/tests/fixtures/.gitignore
components/clarinet-sdk/tests/fixtures/Clarinet.toml
components/clarinet-sdk/tests/fixtures/contracts/counter.clar
components/clarinet-sdk/tests/fixtures/settings/Devnet.toml
components/clarinet-sdk/tests/index.test.ts
components/clarinet-sdk/vitest.config.js

Two commits:
- the first one adds a series of unit test on the compiled clarinet-sdk. More unit-tests should come on the rust side.
- the second one implements the getContractSource method on the clarinet-sdk

feat: clarinet sdk/contracts sources

---

README.md

This works on the documentation portion of #1097

docs: update docs on adding contract requirement

---

docs/feature-guides/test-contract-with-clarinet-sdk.md

docs(sdk): update doc title

---

docs/how-to-guides/how-to-run-integration-environment.md

docs: fix dead link

---

components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/templates/package.json

fix(sdk): template version

---

docs/feature-guides/test-contract-with-clarinet-sdk.md

docs(sdk): review sdk docs

---

components/clarinet-sdk/templates/vitest.config.js

docs: add comment to the vitest config template

---

Cargo.lock
components/clarinet-sdk-wasm/Cargo.toml
components/clarinet-sdk-wasm/src/core.rs
components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json

chore(sdk): bump version and upgrade dependencies

---

Cargo.lock
components/clarinet-sdk-wasm/Cargo.toml

chore(sdk): bump version

---

components/clarinet-cli/src/frontend/cli.rs

docs(cli): udpate hints

---

components/stacks-network/src/orchestrator.rs

Fix regression introduced in #1223
https://github.com/hirosystems/clarinet/pull/1223/files#diff-7d49a496ec370e6ea460d0a24f45f09049a34fdc532a68e39465b2d948f643a3R1002

fix: orchestrator devnet config formatting

---

components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/src/vfs.ts

The project requirements that are written in the directory `.cache/requirements` wouldn't be written by the SDK if the directory didn't exist
Fix: #1222, thanks @lgalabru

fix(sdk): fix requirements loading

---

.github/workflows/ci-clarinet-cli.yaml
.github/workflows/ci.yaml

ci: fix test

---

Cargo.lock
components/clarinet-files/Cargo.toml

chore: ugprade clarinet-file to 2.0.0

---

.github/workflows/ci.yaml

Fix a regression I introduced in #1258 ([diff here](https://github.com/hirosystems/clarinet/commit/d77d27e2d2047475d202d423a23c60eebabe2c27#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR369)).
This part of the job is only triggered once merged on develop, so it wasn't caught during the pr

ci: fix devnet build

---

Cargo.lock
components/clarinet-files/Cargo.toml

chore: bump clarinet-files version

---

components/clarinet-cli/src/frontend/cli.rs

Simply hint copy change
contract publish -> deployments apply

change contract publish -> deployments apply

---

components/clarinet-cli/src/generate/project.rs
components/clarinet-sdk/templates/package.json

chore: update project template package.json

---

components/clarinet-cli/src/generate/project.rs
components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/templates/package.json

Upgrade the clarinet-sdk with vitest 1.x

chore: clarinet-sdk v1.1.0

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-deployments/Cargo.toml
components/clarinet-files/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

chore: bump versions to 2.1.0

---

.github/workflows/ci.yaml

Fix ci regression introduced in #1264

ci: fix clarity repl ci

---

components/stacks-network/src/chains_coordinator.rs

If `stack-stx` is processed during a prepare phase, then the account is not stacked for the next cycle, N, it is stacked for N+1. To deal with that, this change moves the stacking orders earlier in the cycle so that they are processed before the prepare phase.

fix: adjust the timing of the stacking orders

---

components/clarinet-cli/examples/billboard/package-lock.json
components/clarinet-cli/examples/billboard/package.json
components/clarinet-cli/examples/cbtc/package-lock.json
components/clarinet-cli/examples/cbtc/package.json
components/clarinet-cli/examples/counter/package-lock.json
components/clarinet-cli/examples/counter/package.json
components/clarinet-cli/examples/simple-nft/package-lock.json
components/clarinet-cli/examples/simple-nft/package.json
components/clarinet-cli/examples/swappool/package-lock.json
components/clarinet-cli/examples/swappool/package.json
components/clarinet-sdk/package-lock.json

- Upgrade clarinet-sdk dependencies
- Upgrade npm dependencies in cli examples

chore: ugprade npm dependencies

---

components/clarinet-files/src/network_manifest.rs
components/stacks-network/src/ui/app.rs

- Update blocks color in devnet UI, differentiate new nakamoto blocks vs regular "coinbase" blocks
- Update default stacks-node image

refactor: minor nakamoto improvements

---

components/clarinet-cli/src/frontend/cli.rs
components/clarinet-files/src/network_manifest.rs

We decided to keep clarity-wasm off by default

feat: clarity wasm is off by default

---

.github/workflows/ci.yaml
Cargo.lock
components/clarinet-files/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-network/Cargo.toml

- Disable default features for wsts
- Update stacks-core dependencies (that includes [the same change for wsts](https://github.com/stacks-network/stacks-core/pull/4093/commits/fcee50de8c9832a2c84abc684e1fd6c3c42ffeee#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R17))
- Run stacks-devnet-js CI on all targets in PRs, to catch issues earlier

chore: update dependencies

---

components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json

forgot to bump this version in the latest release commit

chore: bump stacks-devnet-js version

---

components/clarity-repl/Cargo.toml
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json

The version upgrade was forgotten during the last release

Release stacks-devnet-js 2.2.0

---

components/clarity-repl/src/analysis/ast_dependency_detector.rs
components/clarity-repl/src/analysis/ast_visitor.rs
components/clarity-repl/src/analysis/coverage.rs
components/clarity-repl/src/repl/debug/cli.rs
components/clarity-repl/src/repl/debug/mod.rs

Fix clippy warning introduced in rust toolchain 1.75.0

reafactor: clippy

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-deployments/Cargo.toml
components/clarinet-files/Cargo.toml
components/clarinet-sdk-wasm/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

chore: prepare release

---

README.md

Quick discord link fix

---

components/stacks-devnet-js/src/lib.rs

Previously when running `stacks-devnet-js`, a `devnet.log` file was not created as it is in a normal `clarinet devnet start` run. This PR creates that log file and writes devnet events to the file.
Fixes #1361

fix: log to devnet.log file when running js devnet

---

Cargo.lock
components/clarinet-deployments/src/lib.rs
components/clarinet-sdk-wasm/Cargo.toml
components/clarinet-sdk-wasm/src/core.rs
components/clarinet-sdk-wasm/src/utils/events.rs
components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/tests/deployment-plan.test.ts
components/clarinet-sdk/tests/simnet-usage.test.ts
components/clarity-lsp/src/common/state.rs
components/clarity-repl/Cargo.toml
components/clarity-repl/src/repl/boot/mod.rs
components/clarity-repl/src/repl/boot/pox-4.clar
components/clarity-repl/src/repl/datastore.rs
components/clarity-repl/src/repl/interpreter.rs

- update pox-4.clar
- implement pox-locking
- I wanted to split a PR into 2, but the pox-locking unit tests were pushed to wrong one (already merged on main) -> https://github.com/hirosystems/clarinet/pull/1372/files#diff-a4b371d4141fdb859465960f65188b6a26d18a7fe2473425e4133b2648ffe0d8

chore: handle pox-locking in simnet

---

Cargo.lock
components/clarinet-sdk-wasm/Cargo.toml
components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/tests/deployment-plan.test.ts
components/clarinet-sdk/tests/simnet-usage.test.ts
components/clarity-repl/src/repl/boot/pox-3.clar
components/clarity-repl/src/repl/boot/pox-4.clar

chore: update pox contracts

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-deployments/Cargo.toml
components/clarinet-files/Cargo.toml
components/clarinet-sdk-wasm/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

chore: release 2.4.0

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-deployments/Cargo.toml
components/clarinet-files/Cargo.toml
components/clarinet-sdk-wasm/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

chore: release 2.4.1

---

Cargo.lock
components/clarinet-cli/examples/billboard/deployments/default.simnet-plan.yaml
components/clarinet-cli/examples/billboard/package-lock.json
components/clarinet-cli/examples/billboard/package.json
components/clarinet-cli/examples/cbtc/deployments/default.simnet-plan.yaml
components/clarinet-cli/examples/cbtc/package-lock.json
components/clarinet-cli/examples/cbtc/package.json
components/clarinet-cli/examples/counter/deployments/default.simnet-plan.yaml
components/clarinet-cli/examples/counter/package-lock.json
components/clarinet-cli/examples/counter/package.json
components/clarinet-cli/examples/simple-nft/deployments/default.simnet-plan.yaml
components/clarinet-cli/examples/simple-nft/package-lock.json
components/clarinet-cli/examples/simple-nft/package.json
components/clarinet-cli/examples/swappool/deployments/default.simnet-plan.yaml
components/clarinet-cli/examples/swappool/package-lock.json
components/clarinet-cli/examples/swappool/package.json
components/clarinet-cli/examples/swappool/tests/empty.test.ts

chore: update npm dependencies in examples

---

components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarity-vscode/client/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json

- upgrade clarity-sdk version
- upgrade vscode extension version

chore: bump sdk and vscode version

---

components/stacks-network/src/chains_coordinator.rs

handle pox.clar (pox 1) in stacking order

fix: unsafe unwrap

---

CHANGELOG.md
Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-deployments/Cargo.toml
components/clarinet-files/Cargo.toml
components/clarinet-sdk-wasm/Cargo.toml
components/clarity-repl/Cargo.toml
components/stacks-codec/Cargo.toml
components/stacks-devnet-js/Cargo.toml
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
components/stacks-network/Cargo.toml
components/stacks-rpc-client/Cargo.toml

chore: release 2.5.1

---

.github/workflows/pkg-version-bump.yaml

ci: fix homebrew release

---

components/clarinet-sdk-wasm/src/core.rs
components/clarity-repl/src/repl/settings.rs

feat: sdk: init empty session

---

.github/workflows/ci-clarinet-cli.yaml
.github/workflows/ci.yaml

The version is now set in the root Cargo.toml

ci: use workspace version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json

Release v2.6.0 with epoch 2.5 as the default

chore: release 2.6.0

---

components/clarity-repl/src/repl/boot/pox-4.clar

This change is the right version. This is pox-4 as deployed on chain

fix: pox-4

---

components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json

chore: release sdk 2.6.0

---

components/clarinet-cli/src/generate/project.rs

feat: generate `.gitattributes` in projects

---

Cargo.lock

chore: update clar2wasm

---

components/clarity-repl/src/repl/interpreter.rs
components/clarity-repl/src/repl/session.rs

set tenure height on epoch change if great or equal than 3.0

fix: set tenure height on epoch change if great or equal than 3.0

---

Cargo.lock
Cargo.toml
components/stacks-network/src/chains_coordinator.rs

chore: upgrade chainhook dependency

---

components/clarinet-cli/examples/cbtc/serverless/yarn.lock
components/clarinet-sdk/package-lock.json
components/clarinet-sdk/package.json
components/clarinet-sdk/tests/support-clarity-version.test.ts

chore: release sdk 2.7.0

---

components/clarinet-cli/examples/counter/tests/counter.test.ts
components/clarinet-cli/src/frontend/cli.rs
components/clarinet-cli/src/generate/contract.rs
components/clarinet-sdk/browser/README.md
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/README.md
components/clarinet-sdk/node/package.json

docs: fix documentation link

---

components/hiro-system-kit/Cargo.toml

Upgrade time. Possibly fixing an issue when compiling for debian

chore: update time version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-cli/src/generate/project.rs
components/clarinet-sdk-wasm/Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
components/stacks-network/src/chains_coordinator.rs
package-lock.json

chore: release 2.8.0

---

components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarinet-sdk/node/vitest-helpers/src/global.d.ts
package-lock.json

fix: js sdk types

---

Cargo.lock
components/clarinet-sdk/node/tests/fixtures/contracts/counter.clar
components/clarinet-sdk/node/tests/simnet-usage.test.ts

Include a fix in clarity-vm to keep the comments in the ast

chore: update clarity and clarity-wasm

---

components/clarity-repl/src/repl/datastore.rs
components/clarity-repl/src/repl/session.rs

- Bitcoin block time should be 10 minutes, not 30. (#957)
- Add some tests

tests: add block time tests

---

components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json

chore: ugprade clarity-vscode version

---

components/stacks-codec/src/codec.rs

Update SignerMessage codec to match core

fix: update SignerMessage codec

---

components/clarinet-files/src/network_manifest.rs

Have a default stacking order in thec devnet config to make the epoch 3.0 more robust

feat: have a stacking order by default in devnet config

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

2.11.1 comes with small changes to improve epoch 3.0 support

chore: release 2.11.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 2.11.2

---

components/clarity-repl/src/repl/mod.rs

Would cause compilation fail under certain conditions (eg: cargo test)

fix: cargo feature flags

---

Cargo.lock
Cargo.toml
components/clarinet-files/Cargo.toml
components/clarinet-sdk-wasm/Cargo.toml
components/clarinet-sdk/clarinet-sdk.code-workspace
components/clarity-lsp/Cargo.toml
package-lock.json
package.json

Update some dependencies.
Improve wasm and sdk setup

refactor: maintain dependencies

---

.github/workflows/audit-format.yaml
.github/workflows/ci.yaml
Cargo.lock
components/clarity-repl/Cargo.toml
components/clarity-repl/src/repl/datastore.rs
components/clarity-repl/src/repl/interpreter.rs

chore: update stacks-core dependencies

---

CHANGELOG.md

2.10.x and 2.11.x were released in October

docs: update changelog dates

---

README.md
components/clarinet-sdk/node/tests/support-clarity-version.test.ts
components/clarity-lsp/src/common/backend.rs

chore: fix some comments

---

components/clarity-lsp/src/common/requests/completion.rs
components/clarity-lsp/src/common/requests/definitions.rs
components/clarity-lsp/src/common/requests/document_symbols.rs
components/clarity-repl/src/analysis/ast_dependency_detector.rs
components/clarity-repl/src/repl/datastore.rs
components/stacks-devnet-js/src/serde/ser.rs

Address new clippy 1.83 warnings.
Mostly unnecesary lifetimes.

chore: rust 1.83 new clippy lints

---

.github/workflows/ci-sdk.yaml
Cargo.lock
components/clarinet-files/Cargo.toml
components/clarinet-files/src/lib.rs
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarinet-sdk/node/tests/simnet-usage.test.ts
components/clarity-vscode/package.json

ci: run sdk test on multiple platforms

---

README.md

Intended links types concept
---

style(readme): navigating section links

---

components/clarinet-deployments/src/types.rs

fix: avoid empty deployment batches

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 2.13.0

---

CHANGELOG.md

chore: fix changelog.md

---

components/clarinet-sdk/node/package.json
components/clarinet-sdk/node/tests/simnet-usage.test.ts
package-lock.json

chore: run sdk tests with vitest 3.x

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-cli/examples/billboard/package-lock.json
components/clarinet-cli/examples/cbtc/package-lock.json
components/clarinet-cli/examples/counter/package-lock.json
components/clarinet-cli/examples/simple-nft/package-lock.json
components/clarinet-cli/examples/swappool/package-lock.json
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarinet-sdk/node/tests/fixtures/settings/Devnet.toml
components/clarinet-sdk/node/tests/simnet-with-sbtc.test.ts
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 2.15.0

---

components/clarity-repl/src/repl/remote_data/http_request/node.rs

fix: x-hiro-product header for clarinet-sdk

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 2.15.1

---

Cargo.lock
components/stacks-network/src/chains_coordinator.rs
components/stacks-network/src/ui/app.rs

Update dependencies.
One of the cargo audit vuln was fix in chainhook sdk and an other in the PR

chore: update dependencies and fix vulnerabilities

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 2.15.2

---

components/clarinet-format/src/formatter/mod.rs
components/clarinet-format/tests/golden-intended/BNS-V2.clar
components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar
components/clarinet-format/tests/golden-intended/comments.clar
components/clarinet-format/tests/golden-intended/match-or.clar

chore: fmt single line for functions with 1 arg

---

.github/workflows/new-issues.yaml
.github/workflows/pkg-version-bump.yaml

Need to double check the permissions that are set
The winget flow needs rework as well

ci: update gh

---

Cargo.lock
Cargo.toml

Updating chainhook-sdk after the needed update where merged on the default branch over the chainhook repo

chore: upgrade chainhook

---

package-lock.json

chore: upgrade npm dependencies

---

components/clarinet-cli/examples/package-lock.json

chore: update examples npm dependencies

---

components/clarinet-format/src/formatter/mod.rs
components/clarinet-format/tests/golden-intended/BNS-V2.clar
components/clarinet-format/tests/golden-intended/clarity-bitcoin.clar

chore:  preserve comment spacing [#1755]

---

Cargo.lock

chore: upgrade crossbeam

---

.github/workflows/pkg-version-bump.yaml

use  release bot token to open winget release pr

ci: winget release token

---

components/clarinet-format/src/formatter/mod.rs
components/clarinet-format/tests/golden-intended/stackflow.clar
components/clarinet-format/tests/golden/stackflow.clar

fix: trait and eol comment fix

---

.github/workflows/ci.yaml

fix: cargo audit

---

components/clarinet-format/tests/golden.rs

fix: clippy lint

---

components/clarinet-sdk/node/tests/deployment-plan.test.ts
components/clarinet-sdk/node/tests/fixtures/EmptyManifest.toml
components/clarinet-sdk/node/tests/pox-locking.test.ts
components/clarinet-sdk/node/tests/simnet-usage.test.ts
components/clarinet-sdk/node/tests/support-clarity-version.test.ts
components/clarity-repl/src/repl/datastore.rs
components/clarity-repl/src/repl/session.rs

This reverts commit b46b3cb49c8cad57186bdb76c65c111cb4aba3fe.
This PR break some deployment plans https://github.com/hirosystems/clarinet/pull/1787
Will require more investigation

Revert "feat: improve simnet epoch handling (#1787)"

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 3.0.1

---

components/clarinet-cli/examples/billboard/package.json
components/clarinet-cli/examples/cbtc/package.json
components/clarinet-cli/examples/counter/package.json
components/clarinet-cli/examples/package-lock.json
components/clarinet-cli/examples/simple-nft/package.json
components/clarinet-cli/examples/simple-nft/tests/simple-nft.test.ts
components/clarinet-cli/examples/swappool/package.json
package-lock.json

Upgrade examples to clarinet-sdk@3.0

chore: upgrade sdk version in examples

---

components/clarinet-format/src/formatter/mod.rs

fix: comment spacing

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 3.0.2

---

components/clarinet-format/src/formatter/mod.rs

fix: top level newline issue

---

components/clarinet-sdk/node/package.json
package-lock.json

Switch Vitest to dev dependencies in the sdk

fix: vitest as a test dependency

---

components/clarinet-format/src/formatter/mod.rs

- fixes #1821 
Comments treated differently in `to_inner_content` to avoid losing context/positioning

fix: retain comment original start_line

---

components/clarity-vscode/package-lock.json

upgrade clarity-vscode npm dev deps, replace #1838

chore: upgrade clarity vscode dev deps

---

Cargo.lock
components/clarinet-cli/Cargo.toml
components/clarinet-cli/src/generate/contract.rs
components/clarinet-cli/tests/cli.rs

Implement some basic unit tests for:
- clarinet new
- clarinet contract new
- clarinet requirements add

tests: basic cli tests

---

Cargo.lock

chore: upgrade stacks-core dependencies

---

components/clarinet-format/src/formatter/mod.rs
components/clarity-lsp/src/common/backend.rs

- fix #1835 
https://github.com/user-attachments/assets/83097b6c-1ef4-46dc-8074-49e5247b4cfd

fix: document range formatting

---

Cargo.lock
Cargo.toml
components/clarinet-cli/Cargo.toml
components/clarinet-cli/src/frontend/cli.rs
components/clarinet-files/src/project_manifest.rs
components/clarinet-sdk-wasm/src/core.rs
components/clarity-repl/src/repl/debug/mod.rs
components/clarity-repl/src/repl/session.rs
components/stacks-network/Cargo.toml
components/stacks-network/src/orchestrator.rs

I was reviewing #1877 and had some comments, but the PR was merged before I finished. This PR addresses them. Basically, it does:
- Replace `format!("{var}")` with `var.to_string()`
- Clean up one string using `formatdoc!`
- Fix some eagerly evaluated format strings in `ok_or()`

chore: Address my comments on PR #1877

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json
prepare-release.sh

chore: release 3.2.0

---

components/clarity-repl/src/repl/session.rs
components/stacks-network/src/orchestrator.rs

Small PR that fixes an `O(n^2)` string building algorithm in `Session::encode()`. Currently we loop over each byte, rewrite and reallocate the entire string to add a new byte each time, which is very inefficient if we have a large number of bytes to write

perf: Fix `O(n^2)` string generation

---

.github/workflows/ci-sdk.yaml

ci: run clippy for wasm target

---

components/clarinet-files/src/devnet_diff.rs
components/clarinet-files/src/project_manifest.rs

Small details that caught my eyes when investigating one an epoch 3.1 issue

refactor: epoch 3.1 improvements

---

CHANGELOG.md
Cargo.lock
Cargo.toml
components/clarinet-sdk/browser/package.json
components/clarinet-sdk/node/package.json
components/clarity-vscode/package-lock.json
components/clarity-vscode/package.json
components/stacks-devnet-js/package-lock.json
components/stacks-devnet-js/package.json
package-lock.json

chore: release 3.3.0

---

components/clarity-lsp/src/common/backend.rs

Optional per-spec, but nice to have :) https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult

feat: Return version at LSP initialization

---

.github/workflows/ci.yaml

fix: audit

---

components/clarinet-cli/examples/counter/tests/counter.test.ts
components/clarinet-cli/examples/simple-nft/tests/simple-nft.test.ts
components/clarity-jupyter-kernel/src/jupyter/jupyter_message.rs

fix some minor issues in comments
---

chore: fix some minor issues in comments

---

components/clarinet-cli/src/frontend/cli.rs
components/clarinet-cli/src/generate/contract.rs
components/clarinet-cli/src/generate/project.rs
components/clarinet-deployments/src/lib.rs
components/clarinet-files/src/project_manifest.rs
components/clarinet-sdk-wasm/src/core.rs
components/clarity-repl/src/analysis/ast_dependency_detector.rs
components/clarity-repl/src/repl/boot/mod.rs
components/clarity-repl/src/repl/interpreter.rs
components/clarity-repl/src/repl/mod.rs
components/clarity-repl/src/repl/session.rs
components/clarity-repl/src/test_fixtures/clarity_contract.rs

feat: allow 'latest' as epoch and default on new contracts

---

components/clarity-vscode/client/package.json
components/clarity-vscode/package-lock.json

chore: ugprade vscode npm dependencies

---

components/clarinet-files/src/network_manifest.rs
components/clarinet-files/src/project_manifest.rs
components/clarinet-sdk/node/tests/epoch-latest.test.ts
components/clarinet-sdk/node/tests/fixtures/ManifestLatest.toml
components/clarinet-sdk/node/tests/remote-data.test.ts

Adding two tests related to epoch maangements.
I ran these tests during the 3.4.0 release pocess, making me slightly more confident about it

tests: add epoch tests

---

components/stacks-network/src/orchestrator.rs

fix: update docs link

---

README.md

Update the contributing section of the readme.
This could be documented further and improved. But at least i wanted to remove the non-sense / outdated stuff

docs: update readme contributing section

---

components/clarinet-sdk-wasm/src/core.rs
components/clarinet-sdk-wasm/src/ts_types.rs
components/clarinet-sdk/node/package.json
components/clarinet-sdk/node/tests/deployment-plan.test.ts
components/clarinet-sdk/node/tests/fixtures/Clarinet.toml
components/clarinet-sdk/node/tests/fixtures/contracts/counter.clar
components/clarinet-sdk/node/tests/fixtures/contracts/stacks-trace-test.clar
components/clarinet-sdk/node/tests/pox-locking.test.ts
components/clarinet-sdk/node/tests/remote-data.test.ts
components/clarinet-sdk/node/tests/reports.test.ts
components/clarinet-sdk/node/tests/simnet-usage.test.ts
components/clarinet-sdk/node/tests/support-clarity-version.test.ts
components/clarity-repl/src/analysis/coverage_tests.rs
components/clarity-repl/src/repl/hooks/tracer.rs
components/clarity-repl/src/repl/interpreter.rs
components/clarity-repl/src/repl/session.rs
components/clarity-repl/src/uprint.rs
package-lock.json

When a contract call fails in simnet (repl or sdk), it's currently difficult to understand why.
This PR attempts to fix it by showing a stacks trace and a cleanr error when that happens
Note: the sdk is currently limited in terms of stdout or stderr message formatting (color, bold, italic, etc). That should be approached in an other PR.

feat: show stack trace when a contract call fails

---

.github/workflows/ci-sdk.yaml
.github/workflows/ci.yaml

ci: run ci
